/* Chapter 11.9 — Geometry Hints, weaponized as a proof lab. */
export default {id:'lesson-11-7',title:'Geometry Hints: Problem Lab',kicker:'Triangles, a.k.a. Geometry',topicIndex:10,lessonIndex:6,next:'study-path.html',beats:[
 {prompt:'Build the parallel-proving toolkit.',interaction:{type:'match',pairs:[['alternate interiors equal','parallel'],['corresponding angles equal','parallel'],['same-side interiors supplementary','parallel'],['constant distance apart','parallel']]},note:'These are converse tests: angle evidence proves the lines parallel.',coach:['Name the certifying angle pair.']},
 {prompt:'Build the perpendicular-proving toolkit.',interaction:{type:'match',pairs:[['angle in a semicircle','right angle'],['median equals half its side','right triangle'],['Pythagorean equality','right triangle'],['radius bisects chord','perpendicular'],['tangent and radius','perpendicular']]},note:'Competition geometry is often recognizing which exit certifies 90°.',coach:['Use the strongest structure visible.']},
 {prompt:'When should you draw a perpendicular?',interaction:{type:'mcq',options:['When area, heights, or right triangles would help','Whenever ratios appear','Only in circles','Never as an auxiliary line'],correct:0},hint:'Perpendiculars manufacture altitudes and Pythagorean handles.',explain:'For similarity, parallels are often better; for area and trig, perpendiculars usually unlock the figure.',coach:['Choose construction by target.']},
 {prompt:'When should you draw a parallel?',interaction:{type:'mcq',options:['When you need equal angles and similar triangles','When you need circle area','Only in parallelograms','To prove every congruence'],correct:0},hint:'Parallels transport angles.',explain:'A parallel can copy a ratio-bearing triangle into contact with the target segments.',coach:['Aim the parallel at the target ratio.']},
 {prompt:'One auxiliary parallel unlocks two ratios. Order the search.',interaction:{type:'order',items:['Write the target ratios explicitly.','Choose a parallel that copies known angles onto target segments.','Prove the manufactured triangles similar or congruent.','Translate the harvested equalities back to the target.']},hint:'The target tells the construction where to aim.',explain:'Auxiliary lines are designed backward from the desired segments.',coach:['Target → construction → theorem → harvest.']},
 {prompt:'Right triangle AHC, M midpoint of hypotenuse AC. What equality should flash immediately?',interaction:{type:'mcq',options:['HM=MA=MC','AH=HC','AM=AH','All sides equal'],correct:0},hint:'Hypotenuse midpoint is circumcenter.',explain:'The midpoint is equidistant from all three vertices. Hidden right-triangle circumcenter facts often solve angle problems instantly.',coach:['Old fact, new costume.']},
 {prompt:'Perpendicular medians form legs of a new right triangle. If \(AD^2+BE^2=5c^2/4\), find its hypotenuse.',interaction:{type:'fillin',fields:[{label:'hypotenuse',answer:'sqrt(5)c/2',accept:['c√5/2']}]},hint:'Apply Pythagoras to the median legs.',explain:'The length is \(\sqrt{5c^2/4}=c\sqrt5/2\).',coach:['Use the supplied invariant cleanly.']},
 {prompt:'Viviani’s theorem: choose the key method.',interaction:{type:'mcq',options:['Chop the equilateral triangle into three subtriangles and add areas.','Use Pythagoras three times.','Draw a circumcircle.','Measure the distances.'],correct:0},hint:'Distances to sides are altitudes.',explain:'Area decomposition makes the sum of distances appear as one factor.',note:'When several perpendicular distances to sides appear, try chop-and-sum area.',coach:['Choose each side as a base.']},
 {prompt:'Execute Viviani’s proof.',interaction:{type:'order',items:['Join interior point P to the three vertices.','Write subareas \(sd_1/2,sd_2/2,sd_3/2\).','Set their sum equal to whole area \(sh/2\).','Cancel s/2 to get \(d_1+d_2+d_3=h\).']},hint:'All three bases have the same length s.',explain:'The apparently moving distances have a fixed sum: the altitude.',coach:['One area, two decompositions.']},
 {prompt:'Audit a difficult proof.',interaction:{type:'order',items:['Mark every given equality and incidence fact.','Classify the target: angle, equality, ratio, or area.','Choose a construction that manufactures a known theorem.','Check correspondence, dependencies, and omitted cases.']},hint:'Read the diagram before choosing a construction.',explain:'The dependable order is evidence, target, construction, audit. It prevents unmarked assumptions and theorem-dependency loops.',note:'Proof technique is a repeatable workflow, not a flash of inspiration.',coach:['Audit assumptions before celebrating.']},
 {prompt:'Euclid’s project started from how many famous postulates?',interaction:{type:'mcq',options:['Five','Two','Ten','Infinitely many'],correct:0},hint:'The parallel postulate was the controversial fifth.',explain:'Lines through points, extensions, circles, equality of right angles, and a parallel principle underpin classical Euclidean geometry.',note:'The fifth postulate’s alternatives eventually produced non-Euclidean geometry.',coach:['This chapter used consequences of a very small starting set.']},
 {section:'checkpoint',prompt:'Need a length ratio: which engine first?',interaction:{type:'mcq',options:['Similarity','Area only','Visual measurement','A random median'],correct:0},hint:'Ratios are similarity’s output.',explain:'Manufacture equal angles, prove similarity, then harvest ratios.',coach:['Parallel lines often create the needed angles.']},
 {section:'checkpoint',prompt:'Need to certify a right angle from side lengths?',interaction:{type:'mcq',options:['Pythagorean converse','AA similarity','Triangle inequality only','Centroid ratio'],correct:0},hint:'Compare largest-side square with the sum of the others.',explain:'Equality proves the angle opposite the largest side is right.',coach:['Use the converse direction.']},
 {section:'checkpoint',prompt:'Equilateral altitude h; interior distances d₁,d₂,d₃. Find the sum.',interaction:{type:'fillin',fields:[{label:'sum',answer:'h'}]},hint:'Use Viviani’s area decomposition.',explain:'\(d_1+d_2+d_3=h\).',coach:['The point may move; the sum does not.']},
 {section:'checkpoint',prompt:'A proof uses tangent⊥radius to prove the tangent–chord theorem, after deriving tangent⊥radius from tangent–chord. Diagnose it.',interaction:{type:'mcq',options:['Circular reasoning','Valid converse','Casework','Similarity'],correct:0},hint:'Follow dependencies.',explain:'The argument loops back to its own conclusion.',coach:['A theorem cannot stand on its child.']},
 {section:'boss',prompt:'Prove Viviani’s theorem completely.',interaction:{type:'order',items:['Draw segments from P to all vertices.','Use each equilateral side s as a base with heights d₁,d₂,d₃.','Add the three subareas.','Equate to \(sh/2\) and cancel to obtain the fixed sum h.']},hint:'The boss is choosing area before algebra.',explain:'\(s(d_1+d_2+d_3)/2=sh/2\), so \(d_1+d_2+d_3=h\).',walkthrough:['Create three triangles.','Write their areas.','Use that they tile the whole.','Cancel the common scale.'],note:'Theorems are destinations; reusable techniques are the vehicle.',coach:['Chop, sum, compare.']},
]};
