/* Chapter 11.6 — Similar Triangles. Ratios only after correspondence. */
export default {id:'lesson-11-4',title:'Similar Triangles',kicker:'Triangles, a.k.a. Geometry',topicIndex:10,lessonIndex:3,next:'interactive-lesson.html?chapter=11&lesson=5',beats:[
 {prompt:'Zoom a triangle. Track a side, a median, and the area.',interaction:{type:'slider',min:1,max:5,step:.5,value:1,label:'scale k',mustExplore:6,render:k=>({main:`side \(=${k}\), median \(=${k}\), area \(=${(k*k).toFixed(2)}\)`,sub:'Every corresponding length scales by k; area contains two length factors, so it scales by k².'})},note:'Similar means same shape at possibly different scale.',coach:['Separate linear and square scaling.']},
 {prompt:'Why does AA prove similarity but not congruence?',interaction:{type:'mcq',options:['Angles fix shape but leave scale unpinned.','The third angle is unknown.','AA works only for circles.','Sides do not matter in geometry.'],correct:0},hint:'The zoomed triangles keep all angles.',explain:'Two angle pairs force the third, but the triangle can still grow or shrink.',note:'AA is the workhorse similarity criterion.',coach:['Look for the missing length scale.']},
 {prompt:'△ABC~△DEF. Build the correspondence.',interaction:{type:'match',pairs:[['A','D'],['B','E'],['C','F'],['AB','DE'],['BC','EF']]},note:'Write vertex pairing before forming ratios. ABC~DFE would mean something different.',coach:['Position in the name controls pairing.']},
 {prompt:'Which proportion respects that correspondence?',interaction:{type:'mcq',options:['AB/DE=BC/EF','AB/EF=BC/DE','AC/DE=AB/DF','AB/BC=DF/DE'],correct:0},hint:'Keep small/large orientation consistent.',explain:'AB↔DE and BC↔EF. Mixing corresponding positions makes the ratios disagree.',coach:['Annotate each numerator’s partner.']},
 {prompt:'Build the remaining similarity criteria.',interaction:{type:'match',pairs:[['two angle pairs','AA'],['included angle + proportional adjacent sides','SAS similarity'],['three proportional side pairs','SSS similarity']]},note:'SAS similarity needs the angle between the proportional side pairs.',coach:['Correspondence still governs every pair.']},
 {prompt:'DE∥BC inside △ABC. Why is similarity free?',interaction:{type:'order',items:['Mark corresponding angles from DE∥BC.','Mark the shared angle at A.','Apply AA to △ADE and △ABC.','Use the resulting constant side ratio.']},hint:'The parallel creates two matching angle pairs.',explain:'A parallel cutting a triangle is a similarity factory.',note:'This single configuration powers midlines, proportional cuts, and many area ratios.',coach:['Parallel → equal angles → AA.']},
 {prompt:'AD/AB=1/3 and DE=6. Find BC.',interaction:{type:'fillin',fields:[{label:'BC',answer:'18'}]},hint:'Small:large is 1:3.',explain:'Corresponding sides share the scale, so \(BC=3\cdot6=18\).',coach:['Keep ratio orientation consistent.']},
 {prompt:'M and N are side midpoints. If BC=22, find MN.',interaction:{type:'fillin',fields:[{label:'MN',answer:'11'}]},hint:'The midpoint triangle has scale 1/2.',explain:'The midline is parallel to the third side and half its length.',note:'Triangle midline theorem: midpoint connector ∥ third side and has half its length.',coach:['Midpoints create k=1/2.']},
 {prompt:'Altitude CD to the hypotenuse creates how many similar triangles?',interaction:{type:'mcq',options:['Three: △ACD~△ABC~△CBD','Only two','None','Four'],correct:0},hint:'Each small triangle shares an acute angle with the original and has a right angle.',explain:'AA makes all three mutually similar.',note:'See altitude-to-hypotenuse → think three similar triangles immediately.',coach:['Mark right angles, then shared acute angles.']},
 {prompt:'AD=4 and DB=8. Find altitude CD.',interaction:{type:'fillin',fields:[{label:'CD',answer:'4sqrt(2)',accept:['4√2']}]},hint:'Use \(CD^2=AD\cdot DB\).',explain:'\(CD^2=32\), so \(CD=4\sqrt2\). This is a geometric mean.',note:'Also \(AC^2=AD\cdot AB\) and \(BC^2=DB\cdot AB\).',coach:['The altitude is the mean proportional of the hypotenuse pieces.']},
 {prompt:'Angle Bisector Theorem: which ratio is correct?',interaction:{type:'mcq',options:['BX/XC=AB/AC','BX/XC=AC/AB','BX=XC always','AB/BX=AC/BC'],correct:0},hint:'The opposite side splits in the ratio of adjacent sides.',explain:'If AX bisects ∠A, then \(BX:XC=AB:AC\).',coach:['Match each opposite piece to the adjacent side on the same side.']},
 {section:'checkpoint',prompt:'AB:AC=2:3, AX bisects ∠A, and BC=25. Find BX and XC.',interaction:{type:'fillin',fields:[{label:'BX',answer:'10'},{label:'XC',answer:'15'}]},hint:'Five ratio shares total 25.',explain:'Each share is 5; the pieces are 10 and 15.',coach:['Convert ratio parts into actual length.']},
 {section:'checkpoint',prompt:'Side ratio larger:smaller is 3. Find area ratio.',interaction:{type:'fillin',fields:[{label:'area ratio',answer:'9'}]},hint:'Square the length scale.',explain:'Area ratio \(=3^2=9\).',coach:['Area is two-dimensional.']},
 {section:'checkpoint',prompt:'Areas are 24 and 54. Find the larger-to-smaller length ratio.',interaction:{type:'fillin',fields:[{label:'ratio',answer:'3/2',accept:['1.5']}]},hint:'Take the square root of 54/24.',explain:'\(54/24=9/4\), so length ratio \(=3/2\).',coach:['Undo k² with a square root.']},
 {section:'checkpoint',prompt:'Equal angles guarantee similarity for which figures here?',interaction:{type:'mcq',options:['Triangles only','All quadrilaterals','All polygons','Circles only'],correct:0},hint:'Triangle angle sum fixes the third angle and shape.',explain:'AA is special to triangles. Rectangles can share all angles while having different length:width ratios.',coach:['Do not export a triangle theorem to arbitrary polygons.']},
 {section:'boss',prompt:'Given ∠ADM=∠ACD with M on AC, prove \(AD^2=AM\cdot AC\).',interaction:{type:'order',items:['Mark the given angle pair.','Mark the shared angle at A.','Use AA: △ADM~△ACD.','Write AD/AM=AC/AD and cross-multiply.']},hint:'The desired product suggests a similarity proportion.',explain:'Correct correspondence yields \(AD^2=AM\cdot AC\). The geometric-mean pattern does not require a right triangle.',walkthrough:['Find two angle pairs.','State triangles in matching order.','Choose a proportion containing AD twice.','Cross-multiply.'],note:'When the target is a product of segments, hunt for similar triangles and a mean proportion.',coach:['Work backward from the algebraic shape.']},
]};
