/* Chapter 11.8 — Area, where the Pythagoras and k² IOUs are paid. */
export default {id:'lesson-11-6',title:'Area and the Proofs Come Due',kicker:'Triangles, a.k.a. Geometry',topicIndex:10,lessonIndex:5,next:'interactive-lesson.html?chapter=11&lesson=7',beats:[
 {prompt:'Build \([ABC]=ah_a/2\) from right triangles.',interaction:{type:'order',items:['Drop altitude \(h_a\).','Write the two small right-triangle areas.','Add them.','Combine their base pieces into a.']},hint:'The same height serves both pieces.',explain:'The sum is \((x h_a+(a-x)h_a)/2=ah_a/2\).',note:'For an obtuse triangle, subtract the outside right triangle; the formula survives.',coach:['Pair an altitude with the side it meets perpendicularly.']},
 {prompt:'Why is \(K=ab\sin C/2\) the same formula?',interaction:{type:'order',items:['Drop altitude from the endpoint of side b.','Write \(\sin C=h_a/b\).','Rearrange \(h_a=b\sin C\).','Substitute into \(K=ah_a/2\).']},hint:'Sine hides the altitude.',explain:'Substitution gives \(K=ab\sin C/2\).',note:'The angle must be included between sides a and b.',coach:['Find which altitude the sine produces.']},
 {prompt:'Sides 8 and 5 include angle C with sinC=3/4. Find area.',interaction:{type:'fillin',fields:[{label:'K',answer:'15'}]},hint:'Use the sine-area formula.',explain:'\(K=8\cdot5\cdot(3/4)/2=15\).',coach:['Included angle only.']},
 {prompt:'Prove \(K=rs\) by decomposition.',interaction:{type:'order',items:['Join incenter I to all vertices.','Drop perpendicular inradii to the sides.','Write subareas \(ar/2,br/2,cr/2\).','Add to \(r(a+b+c)/2=rs\).']},hint:'All three small triangles share height r.',explain:'The incircle turns one area into three base-times-height pieces.',note:'Chop-and-sum is a reusable proof technique, not a one-formula trick.',coach:['Distances from I to all sides are equal.']},
 {prompt:'Perimeter 40, area 120. Find inradius.',interaction:{type:'fillin',fields:[{label:'r',answer:'6'}]},hint:'Semiperimeter is 20.',explain:'\(120=20r\), so \(r=6\).',coach:['Use s, not full perimeter.']},
 {prompt:'Pick the formula from the data.',interaction:{type:'match',pairs:[['base + altitude','ah/2'],['two sides + included angle','ab sinC/2'],['inradius + semiperimeter','rs']]},note:'Strategy begins by inventorying the givens.',coach:['Do not force your favorite formula.']},
 {prompt:'Pay the k² IOU.',interaction:{type:'order',items:['Corresponding bases scale by k.','Corresponding altitudes also scale by k.','Area ratio is base ratio times altitude ratio.','Therefore area ratio is \(k^2\).']},hint:'Area has two independent length factors.',explain:'\(K_1/K_2=(a_1/a_2)(h_1/h_2)=k^2\).',note:'Every corresponding length scales by k; every area scales by k².',coach:['Two dimensions, two factors.']},
 {prompt:'Pay the Pythagoras IOU with a square dissection.',interaction:{type:'order',items:['Make a square of side a+b from four congruent right triangles.','The central square has side c.','Write \((a+b)^2=4(ab/2)+c^2\).','Expand and cancel 2ab to obtain \(a^2+b^2=c^2\).']},hint:'Compute the same large square in two ways.',explain:'Area dissection turns the algebra identity into the theorem promised in Build 2.',note:'IOU paid: Pythagoras now rests on congruence plus area.',coach:['Large square = four triangles + center.']},
 {prompt:'An 8–15–17 triangle: find area, semiperimeter, and inradius.',interaction:{type:'fillin',fields:[{label:'K',answer:'60'},{label:'s',answer:'20'},{label:'r',answer:'3'}]},hint:'First verify it is right.',explain:'\(K=8\cdot15/2=60\), \(s=20\), and \(r=K/s=3\).',coach:['Check the triple before choosing the formula.']},
 {prompt:'Equilateral altitude 12. Find side and area.',interaction:{type:'fillin',fields:[{label:'side',answer:'8sqrt(3)',accept:['8√3']},{label:'area',answer:'48sqrt(3)',accept:['48√3']}]},hint:'Half is a 30–60–90 triangle.',explain:'\(12=(\sqrt3/2)s\Rightarrow s=8\sqrt3\); area \(=s\cdot12/2=48\sqrt3\).',coach:['Special triangle first, area second.']},
 {prompt:'Equate two formulas to expose a hidden sine.',interaction:{type:'fillin',fields:[{label:'hₐ=3, b=4 → sinC',answer:'3/4'}]},hint:'Set \(ah_a/2=ab\sin C/2\).',explain:'Cancel \(a/2\): \(h_a=b\sin C\), hence \(3/4\).',note:'Area formulas form a web; equating them extracts hidden quantities.',coach:['Same area, two expressions.']},
 {section:'checkpoint',prompt:'Similar length ratio 4. Find area ratio.',interaction:{type:'fillin',fields:[{label:'area ratio',answer:'16'}]},hint:'Square 4.',explain:'\(4^2=16\).',coach:['Do not apply k² to lengths.']},
 {section:'checkpoint',prompt:'Area 100, perimeter 50. Find incircle area.',interaction:{type:'fillin',fields:[{label:'circle area',answer:'16pi',accept:['16π']}]},hint:'s=25; K=rs.',explain:'\(r=100/25=4\), so incircle area \(=16\pi\).',coach:['Triangle area reveals r.']},
 {section:'checkpoint',prompt:'Regular octagon in unit circle: split into 8 central triangles. Find area.',interaction:{type:'fillin',fields:[{label:'area',answer:'2sqrt(2)',accept:['2√2']}]},hint:'Each triangle has sides 1,1 and included angle 45°.',explain:'\(8\cdot\frac12\sin45^\circ=4\cdot\sqrt2/2=2\sqrt2\).',coach:['Use sine-area eight times.']},
 {section:'checkpoint',prompt:'Which misuse is invalid?',interaction:{type:'mcq',options:['Using ab sinA/2 when A is not included between a and b','Using rs with s as semiperimeter','Using ah/2 with perpendicular h','Checking for a Pythagorean triple'],correct:0},hint:'The sine angle must sit between the chosen sides.',explain:'A non-included angle produces the wrong altitude.',coach:['Trace the altitude from the sine ratio.']},
 {section:'boss',prompt:'A triangle’s area equals altitude \(h_a\) times median \(m_a\) to side a. Prove it is right.',interaction:{type:'order',items:['Set \(h_am_a=ah_a/2\).','Cancel positive \(h_a\) to get \(m_a=a/2\).','Use the median-to-side converse.','Conclude the opposite angle is 90°.']},hint:'Equate the unusual area expression to the standard one.',explain:'The equation forces the median to equal half the side, exactly the right-triangle converse from Build 1.',walkthrough:['Write both area formulas.','Cancel the common altitude.','Recognize the stored theorem.','Classify the triangle.'],note:'The chapter closes a loop: centers and medians now solve an area proof.',coach:['Turn area into a length equality.']},
]};
