/* Chapter 11.7 — Trigonometry built from similarity and special triangles. */
export default {id:'lesson-11-5',title:'Introduction to Trigonometry',kicker:'Triangles, a.k.a. Geometry',topicIndex:10,lessonIndex:4,next:'interactive-lesson.html?chapter=11&lesson=6',beats:[
 {prompt:'Why can “sin 35°” mean one fixed number?',interaction:{type:'slider',min:1,max:8,value:2,label:'scale',mustExplore:6,render:k=>({main:`opposite \(=${3*k}\), hypotenuse \(=${5*k}\), ratio \(=3/5\)`,sub:'Similarity scales numerator and denominator together, so the ratio survives every size.'})},note:'Trig is legal because right triangles sharing an acute angle are similar.',coach:['Watch the ratio, not raw sides.']},
 {prompt:'Build SOH–CAH–TOA.',interaction:{type:'match',pairs:[['sin θ','opposite/hypotenuse'],['cos θ','adjacent/hypotenuse'],['tan θ','opposite/adjacent']]},note:'Opposite and adjacent are relative to the chosen acute angle; the hypotenuse is fixed.',coach:['Point to θ before naming sides.']},
 {prompt:'Build the reciprocal trio without falling for the s↔s trap.',interaction:{type:'match',pairs:[['csc θ','1/sin θ'],['sec θ','1/cos θ'],['cot θ','1/tan θ']]},note:'Cosecant pairs with sine; secant with cosine; cotangent with tangent.',coach:['Read the reciprocal equation, not the first letter.']},
 {prompt:'A and B are complementary. Which cofunction identity is true?',interaction:{type:'mcq',options:['sin A=cos B','sin A=sin B','tan A=tan B','sec A=cos B'],correct:0},hint:'A’s opposite leg is B’s adjacent leg.',explain:'Since \(B=90^\circ-A\), \(\sin A=\cos(90^\circ-A)\).',note:'Cofunctions are the same side ratio viewed from the other acute angle.',coach:['Switch viewpoint, not triangle.']},
 {prompt:'Derive \(\sin^2A+\cos^2A=1\).',interaction:{type:'order',items:['Write \(a^2/c^2+b^2/c^2\).','Combine as \((a^2+b^2)/c^2\).','Use Pythagoras: \(a^2+b^2=c^2\).','Conclude the ratio is 1.']},hint:'Replace trig functions by side ratios.',explain:'The identity is Pythagoras divided by \(c^2\).',note:'Divide by \(\cos^2A\) to get \(1+\tan^2A=\sec^2A\); divide by \(\sin^2A\) for \(1+\cot^2A=\csc^2A\).',coach:['Geometry first, algebra second.']},
 {prompt:'Derive the 45–45–90 triangle.',interaction:{type:'fillin',fields:[{label:'legs 1,1 → hypotenuse',answer:'sqrt(2)',accept:['√2']},{label:'sin45',answer:'sqrt(2)/2',accept:['√2/2']},{label:'tan45',answer:'1'}]},hint:'Use Pythagoras, then rationalize 1/√2.',explain:'The ratio is \(1:1:\sqrt2\), giving \(\sin45=\cos45=\sqrt2/2\) and \(\tan45=1\).',note:'Derive the table from triangles; do not trust upside-down memorization.',coach:['Equal acute angles face equal legs.']},
 {prompt:'Derive the 30–60–90 triangle from an equilateral triangle.',interaction:{type:'order',items:['Start with an equilateral triangle of side 2.','Drop an altitude, bisecting the base into 1 and 1.','Use Pythagoras to find altitude \(\sqrt3\).','Read the ratio \(1:\sqrt3:2\).']},hint:'One altitude creates two congruent right triangles.',explain:'The short leg faces 30°, the long leg faces 60°, and the hypotenuse is 2.',coach:['Sketch it whenever the table blurs.']},
 {prompt:'Fill the 30° column.',interaction:{type:'fillin',fields:[{label:'sin30',answer:'1/2'},{label:'cos30',answer:'sqrt(3)/2',accept:['√3/2']},{label:'tan30',answer:'sqrt(3)/3',accept:['√3/3','1/√3']}]},hint:'Use opposite=1, adjacent=√3, hypotenuse=2.',explain:'The three ratios are \(1/2,\sqrt3/2,\sqrt3/3\).',coach:['The short leg faces 30°.']},
 {prompt:'What happens at the edge of the table?',interaction:{type:'match',pairs:[['sin0°','0'],['cos0°','1'],['sin90°','1'],['cos90°','0'],['tan90°','undefined']]},note:'Tan90° is undefined because cosine is zero: division by zero, not zero.',coach:['Imagine the right triangle flattening.']},
 {prompt:'sin A=7/25. Recover the whole triangle.',interaction:{type:'fillin',fields:[{label:'cos A',answer:'24/25'},{label:'tan A',answer:'7/24'}]},hint:'Recognize 7–24–25.',explain:'A triple turns one ratio into all six without fresh square roots.',coach:['Let opposite=7 and hypotenuse=25.']},
 {prompt:'sec B=4 and adjacent side is 6. Find hypotenuse and opposite side.',interaction:{type:'fillin',fields:[{label:'hypotenuse',answer:'24'},{label:'opposite',answer:'6sqrt(15)',accept:['6√15']}]},hint:'sec=hyp/adj; then Pythagoras.',explain:'Hypotenuse 24; other leg \(\sqrt{24^2-6^2}=6\sqrt{15}\).',coach:['Use the ratio before Pythagoras.']},
 {section:'checkpoint',prompt:'Find sin60°, cos60°, tan60°.',interaction:{type:'fillin',fields:[{label:'sin60',answer:'sqrt(3)/2',accept:['√3/2']},{label:'cos60',answer:'1/2'},{label:'tan60',answer:'sqrt(3)',accept:['√3']}]},hint:'Use the same 1–√3–2 triangle from the other acute angle.',explain:'The opposite and adjacent legs swap from the 30° view.',coach:['Cofunctions provide a check.']},
 {section:'checkpoint',prompt:'Smallest positive x: \(\sin3x=\cos7x\), acute case.',interaction:{type:'fillin',fields:[{label:'x',answer:'9'}]},hint:'Rewrite cosine as sine of a complement.',explain:'\(3x=90-7x\), so \(x=9^\circ\).',coach:['Cofunction before algebra.']},
 {section:'checkpoint',prompt:'Which side is adjacent to A?',interaction:{type:'mcq',options:['The non-hypotenuse side touching A','The side opposite A','Always the longer leg','The hypotenuse'],correct:0},hint:'Adjacent excludes the hypotenuse in trig naming.',explain:'Of the two sides touching A, the leg is adjacent; the other is the hypotenuse.',coach:['Point to the angle first.']},
 {section:'checkpoint',prompt:'Radius 6: chord subtending 60° and chord subtending 90°.',interaction:{type:'fillin',fields:[{label:'60° chord',answer:'6'},{label:'90° chord',answer:'6sqrt(2)',accept:['6√2']}]},hint:'Central triangles are equilateral and 45–45–90.',explain:'The chords are 6 and \(6\sqrt2\).',coach:['Turn chords into triangle sides.']},
 {section:'boss',prompt:'Angles B=45°, C=30°, altitude from A is \(4\sqrt2\). Find BC.',interaction:{type:'fillin',fields:[{label:'BC',answer:'4sqrt(2)+4sqrt(6)',accept:['4√2+4√6']}]},hint:'The altitude creates one 45–45–90 and one 30–60–90 triangle.',explain:'The base pieces are \(4\sqrt2\) and \(4\sqrt6\), so add them.',walkthrough:['Drop the altitude.','Solve the 45° right triangle.','Solve the 30° right triangle.','Add the base pieces.'],note:'Dropping an altitude to manufacture special triangles is the standard trig-geometry move.',coach:['Treat each side separately.']},
]};
