/* Chapter 11.3–11.4 — Triangle Inequality and Pythagoras. */
export default {id:'lesson-11-2',title:'Triangle Inequality and Pythagoras',kicker:'Triangles, a.k.a. Geometry',topicIndex:10,lessonIndex:1,next:'interactive-lesson.html?chapter=11&lesson=3',beats:[
 {prompt:'Try to build a triangle with sides 8, 1, and 11.',body:'A radius-1 circle around one endpoint and radius-11 circle around the other never meet.',interaction:{type:'mcq',options:['Impossible: 8+1<11.','Possible because all lengths are positive.','Possible only as a right triangle.','Exactly one nondegenerate triangle exists.'],correct:0},hint:'Two shorter sides must reach farther than the longest side.',explain:'The two shorter sticks reach only 9 units together, short of 11. No third vertex can satisfy all three distances.',note:'Triangle Inequality: each side is strictly less than the sum of the other two. Equality is a flattened, degenerate triangle.',coach:['Test the longest side against the other two.']},
 {prompt:'Turn three inequalities into one useful interval.',interaction:{type:'order',items:['Start with \(a+c>b\), giving \(c>b-a\).','Use \(b+c>a\), giving \(c>a-b\).','Combine the lower bounds as \(c>|a-b|\).','Use \(c<a+b\) for the upper bound.']},hint:'The two lower bounds collapse into an absolute value.',explain:'Together they give \(|a-b|<c<a+b\).',note:'The two-sided form is the working version of the Triangle Inequality.',coach:['Difference below, sum above.']},
 {prompt:'Sides 7 and 13 are fixed. Which integer values can the third side x take?',interaction:{type:'fillin',fields:[{label:'smallest',answer:'7'},{label:'largest',answer:'19'},{label:'count',answer:'13'}]},hint:'Use \(6<x<20\).',explain:'Integers 7 through 19 work, for 13 possibilities.',note:'Strict inequalities matter: 6 and 20 are degenerate, not triangles.',coach:['Exclude both endpoints.']},
 {prompt:'Choose three distinct lengths from {1,2,3,4,5}. Which triples survive?',interaction:{type:'mcq',options:['{2,3,4}, {2,4,5}, {3,4,5}','Every triple','Only {3,4,5}','{1,2,3} and {2,3,5}'],correct:0},hint:'For each sorted triple, test only whether the two smaller sum past the largest.',explain:'Systematic casework leaves exactly the three listed triples.',note:'For sorted sides \(a\le b\le c\), only \(a+b>c\) can fail.',coach:['Sort first; one check then suffices.']},
 {prompt:'Pythagoras arrives—with a proof IOU.',interaction:{type:'reveal',face:'Right triangle with legs a,b and hypotenuse c',cta:'Open theorem',hidden:'\(a^2+b^2=c^2\). We use it now; Chapter 11.8 pays the proof debt with a square dissection.'},note:'Always locate the right angle before naming the hypotenuse.',coach:['The hypotenuse is opposite 90°, not merely the longest-looking side.']},
 {prompt:'Legs 8 and 4: simplify the hypotenuse completely.',interaction:{type:'fillin',fields:[{label:'c',answer:'4sqrt(5)',accept:['4√5']}]},hint:'\(c^2=80\); factor a perfect square from the radical.',explain:'\(c=\sqrt{64+16}=\sqrt{80}=4\sqrt5\).',note:'Geometry does not suspend Chapter 1 simplification rules.',coach:['Factor 80 as 16·5.']},
 {prompt:'If ∠A+∠B=90°, which angle is right?',interaction:{type:'mcq',options:['∠C, because the triangle total is 180°.','∠A automatically','∠B automatically','No angle is right'],correct:0},hint:'Use all three angles.',explain:'\(C=180-(A+B)=90^\circ\). The right angle sometimes has to be discovered before Pythagoras can fire.',coach:['Find the right angle; then name the hypotenuse.']},
 {prompt:'Betweenness as an “if and only if.” Put the hard direction in order.',interaction:{type:'order',items:['Assume X is not on segment BC and drop perpendicular XY to BC.','In right triangles, \(XB>YB\) and \(XC>YC\).','Therefore \(XB+XC>YB+YC\).','Since \(YB+YC\ge BC\), equality \(XB+XC=BC\) is impossible.']},hint:'A bent path is longer than its horizontal shadow.',explain:'Thus equality happens exactly when X lies on segment BC. Each direction of an iff requires its own proof.',note:'Logic card: “P iff Q” means prove P→Q and Q→P separately.',coach:['Use hypotenuse > leg twice.']},
 {prompt:'Diagnose the largest angle from side lengths.',interaction:{type:'match',pairs:[['\(c^2<a^2+b^2\)','acute'],['\(c^2=a^2+b^2\)','right'],['\(c^2>a^2+b^2\)','obtuse']]},note:'The comparison is valid when c is the largest side. It is a Pythagorean trichotomy.',coach:['Largest side faces largest angle.']},
 {prompt:'Build the triple library.',interaction:{type:'match',pairs:[['3, 4','5'],['5, 12','13'],['7, 24','25'],['8, 15','17']]},note:'Scale triples multiplicatively: \((na,nb,nc)\). Adding the same number does not preserve squares.',coach:['Spot ratios before doing large arithmetic.']},
 {prompt:'Hypotenuse 175, leg 49. Find the other leg without squaring 175.',interaction:{type:'fillin',fields:[{label:'leg',answer:'168'}]},hint:'49:175=7:25.',explain:'Recognize 7–24–25 scaled by 7. The missing leg is \(24\cdot7=168\).',note:'Ratio spotting is a speed skill and an error-control skill.',coach:['Reduce the known side pair.']},
 {section:'checkpoint',prompt:'Sides 9√2 and 12√2 are legs. Find the hypotenuse.',interaction:{type:'fillin',fields:[{label:'c',answer:'15sqrt(2)',accept:['15√2']}]},hint:'This is 3:4 scaled by 3√2.',explain:'The 3–4–5 pattern gives \(5(3\sqrt2)=15\sqrt2\).',coach:['Factor out the common scale.']},
 {section:'checkpoint',prompt:'Largest side is 10; the others are 6 and 7. Classify the triangle.',interaction:{type:'mcq',options:['Obtuse','Right','Acute','Degenerate'],correct:0},hint:'Compare 100 with 36+49.',explain:'\(100>85\), so the largest angle is obtuse.',coach:['Square the largest side separately.']},
 {section:'checkpoint',prompt:'Which can be the third side when two sides are 5 and 12?',interaction:{type:'mcq',options:['10','7','17','18'],correct:0},hint:'\(7<c<17\).',explain:'Only 10 lies strictly between 7 and 17.',coach:['Difference below, sum above.']},
 {section:'checkpoint',prompt:'A 25-foot ladder has its foot 7 feet from a wall. Find the height.',interaction:{type:'fillin',fields:[{label:'height',answer:'24'}]},hint:'Recognize 7–24–25.',explain:'\(h=24\). If the top later falls to 20, the foot moves to 15 via 15–20–25.',coach:['Look for a triple before squaring.']},
 {section:'boss',prompt:'The ladder top slips from 24 feet to 20 feet while its length stays 25. How far does the foot slide?',interaction:{type:'fillin',fields:[{label:'feet',answer:'8'}]},hint:'Find the old and new horizontal legs.',explain:'Old foot distance 7 from 7–24–25. New distance 15 from 15–20–25. It slides \(15-7=8\) feet.',walkthrough:['Use the first right triangle to get 7.','Use the second to get 15.','Compare positions, not hypotenuses.','Subtract 8.'],note:'One applied problem can hide two different scaled triples.',coach:['Draw both states separately.']},
]};
