/* Chapter 11.5 — Congruent Triangles. Correspondence before criteria. */
export default {id:'lesson-11-3',title:'Congruent Triangles',kicker:'Triangles, a.k.a. Geometry',topicIndex:10,lessonIndex:2,next:'interactive-lesson.html?chapter=11&lesson=4',beats:[
 {prompt:'△ABC≅△DEF. Which angle equals ∠B—and which side equals AC?',interaction:{type:'mcq',options:['∠E and DF','∠D and DE','∠F and EF','∠E and DE'],correct:0},hint:'Read positions: first↔first, second↔second, third↔third.',explain:'A↔D, B↔E, C↔F. Thus ∠B=∠E and AC=DF.',note:'Congruence order is a correspondence contract, not decoration.',coach:['Write the vertex pairing before extracting parts.']},
 {prompt:'Build the four general criteria.',interaction:{type:'match',pairs:[['three sides','SSS'],['two sides + included angle','SAS'],['two angles + included side','ASA'],['two angles + another side','AAS']]},note:'Included means physically between the two other marked parts.',coach:['Read each acronym in diagram order.']},
 {prompt:'Why is SSS rigid?',interaction:{type:'mcq',options:['Three fixed sticks can close in only one shape, up to reflection.','All triangles with one equal side are congruent.','Angles never matter.','SSS is a similarity criterion only.'],correct:0},hint:'Imagine hinging two sticks; the third fixes the opening.',explain:'The third side removes the hinge freedom. Reflection changes orientation, not size or shape.',coach:['Ask what motion remains after each constraint.']},
 {prompt:'Why is SAS rigid?',interaction:{type:'mcq',options:['The included angle fixes the hinge between the two known sides.','Any angle works, included or not.','The third side is irrelevant.','SAS is the same as SSA.'],correct:0},hint:'The angle must sit between the known sides.',explain:'Two fixed sides hinged at a fixed included angle force the third side and entire triangle.',note:'A non-included angle leaves the ambiguous swing alive.',coach:['Find the hinge.']},
 {prompt:'Perform the SSA autopsy.',interaction:{type:'mcq',options:['The swinging side may hit the target ray in two places, producing two triangles.','SSA always works.','SSA fails only for equilateral triangles.','SSA gives no triangle ever.'],correct:0},hint:'A circle can intersect a ray twice.',explain:'The same two sides and non-included angle can produce an acute or obtuse solution. There is no general SSA criterion.',note:'Warning card: <b>SSA does not exist</b> as a general congruence theorem.',coach:['Picture the unfixed side swinging.']},
 {prompt:'Why does AAS reduce to ASA?',interaction:{type:'order',items:['Mark two equal angle pairs.','Use the 180° sum to prove the third angle pair equal.','Now the known side lies between some corresponding angle pair.','Apply ASA.']},hint:'Triangles give the missing angle for free.',explain:'Two angles determine the third, so any corresponding side fixes scale.',coach:['Angle sum supplies what the acronym seems to lack.']},
 {prompt:'Right-triangle criteria: match each to its data.',interaction:{type:'match',pairs:[['two legs','LL'],['hypotenuse + one leg','HL'],['one side + one acute angle','SA']]},note:'LL is SAS because the included angle is 90°. SA is ASA/AAS with the right angle already known.',coach:['The right angle is hidden data.']},
 {prompt:'HL looks like forbidden SSA. Why does it survive?',interaction:{type:'mcq',options:['Pythagoras determines the missing leg, converting the data to SSS.','SSA becomes valid whenever a diagram looks right.','The hypotenuse is an angle.','Reflection creates a different triangle.'],correct:0},hint:'Hypotenuse and one leg determine the other leg.',explain:'The right angle destroys the two-position ambiguity. The missing leg is \(\sqrt{h^2-\ell^2}\), uniquely fixed.',note:'HL is the exception that explains the rule.',coach:['Use Pythagoras as the rigidity mechanism.']},
 {prompt:'The congruence workflow belongs in this order.',interaction:{type:'order',items:['Mark all given equal parts.','Choose candidate triangles and write correspondence.','Name the valid criterion.','Harvest the remaining corresponding parts.']},hint:'Do not hunt a criterion before reading the marks.',explain:'Congruence is a vending machine: prove it once, extract corresponding equalities afterward.',note:'CPCTC in spirit: corresponding parts of congruent triangles are equal.',coach:['Marks → triangles → criterion → harvest.']},
 {prompt:'Prove equal sides imply equal base angles.',interaction:{type:'order',items:['Drop altitude AD from the vertex to the base.','The two right triangles share AD and have equal hypotenuses.','Apply HL.','Harvest the equal base angles.']},hint:'Split one isosceles triangle into a congruent pair.',explain:'The altitude manufactures right triangles, and HL converts side equality into angle equality.',note:'Isosceles theorem: equal sides ⇔ equal opposite angles. Each direction needs proof.',coach:['Create triangles that contain the target angles.']},
 {prompt:'Circle crossover: radius OT is perpendicular to chord AB. What follows?',interaction:{type:'mcq',options:['AT=TB','AB is a diameter','OA=AB','The chord is tangent'],correct:0},hint:'Compare right triangles OTA and OTB.',explain:'OA=OB are radii, OT is shared, and both triangles are right; HL gives AT=TB.',note:'Radius perpendicular to chord ⇔ radius bisects chord.',coach:['Radii are the “what’s special” trigger.']},
 {section:'checkpoint',prompt:'Three angle pairs are equal, but one triangle is twice as large. Classify the relation.',interaction:{type:'mcq',options:['Similar, not congruent','Congruent by AAA','Congruent by SSA','Unrelated'],correct:0},hint:'Angles fix shape, not scale.',explain:'AAA/AA supports similarity only.',coach:['Ask what pins length.']},
 {section:'checkpoint',prompt:'Right triangles have hypotenuses 13 and one corresponding leg 5. Which criterion?',interaction:{type:'mcq',options:['HL','SSA','LL','AA'],correct:0},hint:'Use the specialized right-triangle name.',explain:'Equal hypotenuse plus equal leg gives HL.',coach:['Do not call it generic SSA.']},
 {section:'checkpoint',prompt:'△ABC≅△BAD. In △ABC, angles A and B are 70° and 60°. Find corresponding ∠D.',interaction:{type:'fillin',fields:[{label:'∠D',answer:'50'}]},hint:'Find the third angle, then use correspondence.',explain:'The third angle is \(180-70-60=50^\circ\), which corresponds to D.',coach:['Compute before harvesting.']},
 {section:'checkpoint',prompt:'Which data is insufficient?',interaction:{type:'mcq',options:['SSA','SSS','SAS','AAS'],correct:0},hint:'Look for the ambiguous case.',explain:'SSA can describe two different triangles.',coach:['Find whether the angle is included.']},
 {section:'boss',prompt:'Prove the converse isosceles theorem: if ∠B=∠C, then AB=AC.',interaction:{type:'order',items:['Drop altitude AD to BC.','Mark the two right angles and the given base-angle equality.','Use SA/AAS on triangles ABD and ACD.','Harvest AB=AC.']},hint:'Manufacture two right triangles.',explain:'The altitude creates a congruent pair; correspondence turns equal angles into equal opposite sides.',walkthrough:['Draw AD⊥BC.','Record ∠B=∠C.','Use the shared altitude with right-triangle congruence.','Extract AB=AC.'],note:'The Chapter 10 isosceles “loan” is now paid in both directions.',coach:['Split, prove, harvest.']},
]};
