/* Chapter 11.1–11.2 — Classification and the Four Centers. */

const BASE_TRIANGLE={view:{x:-7,y:-5,w:14,h:12},alt:'A fully draggable triangle ABC',points:[{id:'A',x:-5,y:-2,label:'A',draggable:true},{id:'B',x:5,y:-2,label:'B',draggable:true},{id:'C',x:0,y:5,label:'C',draggable:true}],segments:[{id:'AB',from:'A',to:'B'},{id:'BC',from:'B',to:'C'},{id:'CA',from:'C',to:'A'}]};
const MEDIAN_FIG={view:{x:-7,y:-5,w:14,h:12},alt:'Triangle ABC with midpoint D and median AD',points:[{id:'A',x:0,y:5,label:'A'},{id:'B',x:-6,y:-3,label:'B'},{id:'C',x:6,y:-3,label:'C'},{id:'D',x:0,y:-3,label:'D'},{id:'G',x:0,y:0.333,label:'G',draggable:true,constrain(x,y){return[0,Math.max(-3,Math.min(5,y))];}}],segments:[{id:'AB',from:'A',to:'B'},{id:'AC',from:'A',to:'C'},{id:'BC',from:'B',to:'C'},{id:'AD',from:'A',to:'D'}]};
const RIGHT_FIG={view:{x:-2,y:-2,w:12,h:10},alt:'Right triangle ABC with hypotenuse BC and midpoint M',points:[{id:'A',x:0,y:0,label:'A'},{id:'B',x:0,y:6,label:'B'},{id:'C',x:8,y:0,label:'C'},{id:'M',x:4,y:3,label:'M'}],segments:[{id:'AB',from:'A',to:'B'},{id:'AC',from:'A',to:'C'},{id:'BC',from:'B',to:'C'},{id:'AM',from:'A',to:'M',dashed:true}]};

export default {id:'lesson-11-1',title:'Classification and the Four Centers',kicker:'Triangles, a.k.a. Geometry',topicIndex:10,lessonIndex:0,next:'interactive-lesson.html?chapter=11&lesson=2',beats:[
  {prompt:'Drag the triangle. It needs two classifications, not one.',body:'Side type and angle type answer different questions. An isosceles right triangle is allowed.',interaction:{type:'geometry',mode:'drag',mustExplore:12,tools:['protractor','mark'],instruction:'Drag all three vertices; compare side lengths.',figure:BASE_TRIANGLE,measure:s=>`\(AB=${s.dist('A','B').toFixed(2)},\ BC=${s.dist('B','C').toFixed(2)},\ CA=${s.dist('C','A').toFixed(2)}\)`},note:'By sides: equilateral, isosceles, scalene. By angles: acute, right, obtuse. Every triangle belongs to one category from each list.',coach:['Compare sides first; then locate the largest angle.']},
  {prompt:'An equilateral triangle has three equal angles. Find each one.',interaction:{type:'fillin',fields:[{label:'each angle',answer:'60'}]},hint:'Equal angles share the 180° total equally.',explain:'\(3x=180^\circ\), so \(x=60^\circ\). Equilateral implies equiangular—and later congruence proves the converse.',note:'Right-triangle vocabulary: the side opposite 90° is the hypotenuse; the other two are legs.',coach:['Use symmetry plus the triangle sum.']},
  {prompt:'In △ABC, tap side a.',interaction:{type:'geometry',mode:'identify',target:'BC',instruction:'Lowercase side a lies opposite uppercase A.',figure:BASE_TRIANGLE},hint:'Find the only side that does not touch A.',explain:'Side \(a=BC\), side \(b=CA\), and side \(c=AB\). The opposite-letter convention keeps formulas compact.',note:'Perimeter \(p=a+b+c\); semiperimeter \(s=p/2\). The semiperimeter becomes central in area and incircle formulas.',coach:['Opposite means “does not contain the vertex.”']},
  {prompt:'Median anatomy: drag G until \(AG:GD=2:1\).',interaction:{type:'geometry',mode:'drag',goal:s=>Math.abs(s.dist('A','G')/s.dist('G','D')-2)<.05,tools:['mark'],instruction:'Place G at the centroid position on median AD.',figure:MEDIAN_FIG,measure:s=>`\(AG/GD=${(s.dist('A','G')/Math.max(.001,s.dist('G','D'))).toFixed(2)}\)`},hint:'The centroid is two thirds of the way from vertex A to midpoint D.',success:'The ratio locks at 2:1.',note:'A median joins a vertex to the opposite midpoint. All three medians concur at centroid G, which divides each median <b>2:1 from the vertex</b>.',coach:['Split AD into three equal shares; AG takes two.']},
  {prompt:'Which statement defines the angle-bisector locus?',interaction:{type:'mcq',options:['Every point on an angle bisector is equidistant from the two sides.','Every point is equidistant from the two vertices.','The bisector is always a median.','The bisector contains only one point.'],correct:0},hint:'Distance to a line is measured perpendicularly.',explain:'Points equidistant from the two sides lie on the angle bisector, and every point on the bisector has those equal distances.',note:'The locus viewpoint turns concurrency into transitivity of equal distances.',coach:['Sides, not endpoints, belong to the incenter story.']},
  {prompt:'Run the incenter concurrency proof.',interaction:{type:'order',items:['Let I lie on the bisectors of angles A and B.','From A’s bisector, I is equidistant from sides AB and AC.','From B’s bisector, I is equidistant from sides BA and BC.','Therefore I is equidistant from AC and BC, so it lies on C’s bisector.']},hint:'Use AB as the shared distance bridge.',explain:'Equal-to-the-same-distance closes the third relation. The three bisectors concur at I.',note:'The incenter is equidistant from <b>sides</b>; perpendicular radii to those sides form the incircle and inradius r.',coach:['Chain side distances through AB.']},
  {prompt:'Now swap SIDES for VERTICES. What locus appears?',interaction:{type:'mcq',options:['The perpendicular bisector of a segment','An angle bisector','A median','An altitude'],correct:0},hint:'Which line contains all points equally far from A and B?',explain:'The perpendicular bisector of AB is exactly the set of points P satisfying PA=PB.',note:'Perpendicular bisectors concur at circumcenter O, equidistant from <b>vertices</b>; OA=OB=OC=R.',coach:['Incenter → sides. Circumcenter → vertices.']},
  {prompt:'Where can the circumcenter live?',interaction:{type:'match',pairs:[['acute triangle','inside'],['right triangle','midpoint of hypotenuse'],['obtuse triangle','outside']]},note:'Centers are not guaranteed to lie inside. Dragging a triangle through acute, right, and obtuse states is a location safari, not a cosmetic exercise.',coach:['Think about where perpendicular bisectors must meet.']},
  {prompt:'Altitudes are perpendiculars from vertices. Where is H in a right triangle?',interaction:{type:'mcq',options:['At the right-angle vertex','At the hypotenuse midpoint','Always outside','At the centroid'],correct:0},hint:'Two sides of a right triangle are already perpendicular.',explain:'The two legs themselves are altitudes, so they intersect at the right-angle vertex. In an obtuse triangle, altitude extensions meet outside.',note:'The three altitudes concur at orthocenter H. Do not conflate altitude, median, and angle bisector.',coach:['Identify which sides already satisfy the altitude definition.']},
  {prompt:'Match each center to the construction that creates it.',interaction:{type:'match',pairs:[['centroid G','medians'],['incenter I','angle bisectors'],['circumcenter O','perpendicular bisectors'],['orthocenter H','altitudes']]},note:'Memory anchor: G balances mass; I touches sides; O circles vertices; H is built from heights.',coach:['Name what each center is equidistant from—or what lines define it.']},
  {prompt:'Right-triangle payoff: tap the hypotenuse midpoint M.',interaction:{type:'geometry',mode:'identify',target:'M',instruction:'Tap the circumcenter.',figure:RIGHT_FIG},hint:'An angle in a semicircle is right.',explain:'Because ∠A=90°, BC is a diameter of the circumcircle. Its midpoint M is the circumcenter.',note:'In a right triangle, circumradius = half the hypotenuse, and the median to the hypotenuse has that same length.',coach:['Turn the semicircle theorem backward.']},
  {section:'checkpoint',prompt:'A right triangle has hypotenuse 18. Find R and the median to the hypotenuse.',interaction:{type:'fillin',fields:[{label:'R',answer:'9'},{label:'median',answer:'9'}]},hint:'Both run from the midpoint/circumcenter to a vertex.',explain:'The hypotenuse is a diameter, so \(R=18/2=9\). The median is a radius, also 9.',coach:['One fact answers both blanks.']},
  {section:'checkpoint',prompt:'Which center is equidistant from all three sides?',interaction:{type:'mcq',options:['Incenter','Circumcenter','Centroid','Orthocenter'],correct:0},hint:'Its circle touches the sides.',explain:'The incenter has equal perpendicular distances to all three sides.',coach:['Incircle → incenter.']},
  {section:'checkpoint',prompt:'An isosceles non-equilateral triangle has how many distinct lines among its medians, angle bisectors, and altitudes?',interaction:{type:'fillin',fields:[{label:'lines',answer:'7'}]},hint:'The symmetry axis belongs to all three families.',explain:'One shared symmetry line plus two remaining medians, two bisectors, and two altitudes gives \(1+2+2+2=7\).',coach:['Count coincident lines only once.']},
  {section:'checkpoint',prompt:'Perpendicular bisectors of two sides meet on the third side. Classify the triangle.',interaction:{type:'mcq',options:['Right','Equilateral','Obtuse only','Impossible'],correct:0},hint:'Their intersection is the circumcenter.',explain:'A circumcenter on a side makes that side a diameter of the circumcircle, so the opposite angle is right.',coach:['Run the location safari backward.']},
  {section:'boss',prompt:'Converse challenge: in △ABC, M is the midpoint of BC and \(AM=BM\). Prove ∠A is right.',interaction:{type:'order',items:['Use midpoint: \(BM=CM\).','Combine with \(AM=BM\) to get \(AM=BM=CM\).','Recognize M as the center of a circle through A, B, and C.','BC is a diameter, so the inscribed angle A is 90°.']},hint:'Three equal distances manufacture a circumcircle.',explain:'The hypothesis says the median equals half the side. That makes M the circumcenter on BC, and the semicircle theorem forces a right angle.',walkthrough:['Mark BM=CM.','Add AM to the equality chain.','Draw the circle centered at M.','Apply the diameter/semicircle theorem.'],note:'This converse is a competition workhorse: median to a side = half that side ⇔ opposite angle is right.',coach:['Turn length equalities into a circle.']},
]};
