const mcq=(prompt,options,correct,explain,section='learn')=>({section,prompt,interaction:{type:'mcq',options,correct},hint:'Use the parallel marks before choosing an angle family.',explain,note:explain,coach:['Locate the transversal.','Decide whether the angles are inside, outside, or matching corners.']});
const fill=(prompt,fields,explain,section='checkpoint')=>({section,prompt,interaction:{type:'fillin',fields},hint:'Mark equal angles, then use a straight line or triangle sum.',explain,coach:['Write one local equation.','Carry that value to the target.']});
export default {id:'lesson-10-2',title:'Parallel Lines and the Triangle’s 180°',kicker:'Angles',topicIndex:9,lessonIndex:1,next:'interactive-lesson.html?chapter=10&lesson=3',beats:[
 {prompt:'Drag the transversal. Which angles move in lockstep?',interaction:{type:'geometry',mode:'drag',mustExplore:8,tools:['mark','protractor'],figure:{view:{x:-7,y:-6,w:14,h:12},alt:'Two parallel lines crossed by a draggable transversal',points:[{id:'L1',x:-6,y:3,hidden:true},{id:'L2',x:6,y:3,hidden:true},{id:'M1',x:-6,y:-3,hidden:true},{id:'M2',x:6,y:-3,hidden:true},{id:'T1',x:-2,y:5,label:'A',draggable:true},{id:'T2',x:2,y:-5,label:'B'}],lines:[{id:'l',from:'L1',to:'L2',label:'ℓ'},{id:'m',from:'M1',to:'M2',label:'m'},{id:'t',from:'T1',to:'T2',label:'t'}]},measure:s=>{const p=s.points;let a=Math.atan2(p.T1.y-p.T2.y,p.T1.x-p.T2.x)*180/Math.PI;a=Math.abs(a)%180;return `acute angles: \\(${Math.min(a,180-a).toFixed(1)}^\\circ\\); obtuse angles: \\(${Math.max(a,180-a).toFixed(1)}^\\circ\\)`;}},note:'With parallel lines, alternate interior and corresponding angles are equal; same-side interior angles are supplementary.',coach:['Watch groups, not individual labels.']},
 mcq('Which claim needs ℓ ∥ m?',['Alternate interior angles are equal.','Vertical angles are equal.','Angles on a straight line sum to 180°.','A full turn is 360°.'],0,'Vertical and straight-line facts work without parallelism. Alternate-interior equality is the gift of parallel lines.'),
 mcq('If alternate interior α=β and γ is vertical to α, what follows?',['γ=β','γ+β=90°','γ=2β','Nothing'],0,'γ=α by vertical angles and α=β by alternate interiors, so γ=β: corresponding angles emerge from two earlier facts.'),
 {prompt:'Construct the line that makes the triangle angle-sum proof work.',body:'Choose Auxiliary line, then tap C and E.',interaction:{type:'geometry',mode:'drag',mustExplore:1,tools:['auxiliary'],figure:{view:{x:-7,y:-4,w:14,h:10},alt:'Triangle ABC with point E ready for a parallel through C',points:[{id:'A',x:-4,y:-2,label:'A'},{id:'B',x:4,y:-2,label:'B'},{id:'C',x:1,y:3,label:'C',draggable:true},{id:'E',x:6,y:3,label:'E'}],segments:[{id:'AB',from:'A',to:'B'},{id:'AC',from:'A',to:'C'},{id:'BC',from:'B',to:'C'}]}},note:'Draw through C a line parallel to AB. Alternate interior angles move A and B up to C; the three angles on that straight line total 180°.',coach:['A useful auxiliary line manufactures familiar angle pairs.','Connect C to E.']},
 mcq('A triangle has remote interior angles 35° and 62°. Its exterior angle is…',['97°','83°','117°','27°'],0,'Exterior Angle Theorem: exterior = sum of the two remote interior angles = 97°.'),
 mcq('Why do the three exterior angles of a triangle total 360°?',['Walking once around turns your direction through one full turn.','They are the triangle’s interior angles.','Each is 120°.','Every triangle is equilateral.'],0,'The turning argument is visual and generalizes: one trip around any polygon turns through 360°.'),
 {prompt:'Put the angle-chase ritual in order.',interaction:{type:'order',items:['Mark parallel lines and given equal angles.','Transfer angles using alternate interior, corresponding, or vertical angles.','Use straight-line, triangle-sum, or exterior-angle equations.','Check that every claimed parallel relation has parallel marks.']},hint:'Marks come before algebra.',explain:'A diagram is data. Mark it first, transport angles second, solve locally third, audit assumptions last.',note:'Never claim alternate-interior equality unless the lines are known parallel.',coach:['Start by recording what is given.','Audit parallelism at the end.']},
 fill('Checkpoint: a triangle has angles 34° and 71°. Find the third.',[{label:'third angle',answer:'75'}],'180−34−71=75.'),
 fill('Find the exterior angles adjacent to 34°, 71°, and 75°.',[{label:'first',answer:'146'},{label:'second',answer:'109'},{label:'third',answer:'105'}],'Each exterior is 180° minus its adjacent interior. They total 360°.'),
 mcq('A transversal makes corresponding angles 112° and 112°. What may you conclude?',['The two lines are parallel.','The lines are perpendicular.','The angles are complementary.','No conclusion is possible.'],0,'The converse corresponding-angle theorem applies: equal corresponding angles imply the lines are parallel.','checkpoint'),
 fill('Parallel lines: one same-side interior angle is 68°. Find the other.',[{label:'angle',answer:'112'}],'Same-side interior angles are supplementary: 180−68=112.'),
 {section:'boss',prompt:'Two triangles meet at C between parallel lines. Their known angles transport to C as 48° and 37°; the remaining angle between the triangles lies on the same straight line. Find it.',interaction:{type:'fillin',fields:[{label:'angle between them',answer:'95',accept:['95°']}]},hint:'The three adjacent angles form a straight angle.',explain:'48°+x+37°=180°, so x=95°.',walkthrough:['Draw an auxiliary parallel through C.','Transport the two given angles to C using alternate interiors.','Use the straight line: 48+x+37=180.','Solve x=95°.'],coach:['Bring every useful angle to the shared vertex.','Then look for a straight line.']}
]};
