const mcq=(prompt,options,correct,explain,section='learn')=>({section,prompt,interaction:{type:'mcq',options,correct},hint:'Ask what known object the proposed move creates—and whether the fact is already available.',explain,note:explain,coach:['Work backwards from the goal.','Audit theorem dependencies and diagram cases.']});
export default {id:'lesson-10-4',title:'The Burden of Proof',kicker:'Angles',topicIndex:9,lessonIndex:3,next:'study-path.html',beats:[
 {prompt:'Borrow one triangle fact for this studio.',interaction:{type:'reveal',face:'A triangle has two equal sides. What follows?',cta:'Reveal the loan',hidden:'The opposite base angles are equal. Radii of one circle are equal, so triangles made from radii are isosceles.'},note:'Equal sides imply equal opposite angles. Full treatment arrives in the triangles chapter.',coach:['Think symmetry: equal sides face equal angles.']},
 {prompt:'Proof 1: draw the line the inscribed-angle proof needs.',body:'Choose Auxiliary line, then tap A and B. The two radii create an isosceles triangle.',interaction:{type:'geometry',mode:'drag',mustExplore:1,tools:['auxiliary','mark'],figure:{view:{x:-7,y:-7,w:14,h:14},alt:'Circle for an inscribed angle proof',points:[{id:'O',x:0,y:0,label:'O'},{id:'A',x:-5,y:-3.32,label:'A'},{id:'B',x:5,y:-3.32,label:'B'},{id:'C',x:0,y:6,label:'C',draggable:true}],circles:[{id:'c',center:'O',r:6}],segments:[{id:'OA',from:'O',to:'A'},{id:'OB',from:'O',to:'B'},{id:'CA',from:'C',to:'A'},{id:'CB',from:'C',to:'B'}]}},note:'Good auxiliary lines manufacture objects a known theorem can grip: isosceles triangles, inscribed angles, parallels, or cyclic quadrilaterals.',coach:['Connect two existing key points.']},
 mcq('The goal is φ=2θ. What is the best backwards question?',['What intermediate equality would make φ=2θ immediate?','Which angle looks biggest?','Can I assume the diagram is to scale?','Can I use the conclusion now?'],0,'Working backwards identifies the bridge you must prove; it does not assume the goal.'),
 mcq('A proof handles only the case where the center lies outside the inscribed angle. Is it complete?',['No; audit center-inside and center-on-a-side cases.','Yes; one picture proves all cases.','Yes, if the drawing is accurate.','No theorem can have cases.'],0,'A proof owns all configurations allowed by its hypotheses. The other cases may be similar, but they must be checked.'),
 {prompt:'Proof 2: order the two-secant construction.',interaction:{type:'order',items:['Draw the segment joining the two far intersection points.','Recognize the two new inscribed angles.','Use the supplementary angle at the near intersection.','Apply triangle sum and isolate the external angle.']},hint:'The new segment should create angles whose arcs already appear in the goal.',explain:'The auxiliary chord manufactures two inscribed angles; supplementary and triangle-sum equations then produce half the arc difference.',note:'An auxiliary line is not magic. Its job is to create known objects.',coach:['Choose the line based on the theorem you want to use.']},
 mcq('While proving tangent–chord, may you use “tangent ⟂ radius” if that fact was proved earlier from tangent–chord?',['No; that is circular reasoning.','Yes; true statements may always prove each other.','Yes, if the picture looks right.','Only for acute angles.'],0,'A theorem cannot stand on one of its own consequences. Track dependency order.'),
 mcq('What closes the correct tangent–chord proof after adding a chord?',['Exterior Angle Theorem plus inscribed-angle facts','Pythagorean Theorem','Slope formula','Area of a sector'],0,'The exterior angle equals the sum of the remote interiors; those interiors translate into half-arcs.'),
 mcq('Checkpoint: which auxiliary line is strongest for two chords crossing inside?',['Join two endpoints to create a triangle and two inscribed angles.','Draw a random radius.','Draw a diameter unrelated to the angle.','Add no line and measure the picture.'],0,'The endpoint chord creates theorem-ready inscribed angles.','checkpoint'),
 mcq('Spot the circular argument.',['Prove A from B, after B was previously proved using A.','Use vertical angles after proving them from straight lines.','Use a definition in a proof.','Split a proof into cases.'],0,'The first argument loops: its support eventually depends on its own conclusion.','checkpoint'),
 mcq('Center O lies on one side of an inscribed angle. Which ingredients give the short proof?',['One isosceles triangle and the Exterior Angle Theorem','Sector area and arc length','Two-secant difference','Coordinate slopes'],0,'The radius triangle is isosceles, and the central angle is an exterior angle.','checkpoint'),
 {section:'checkpoint',prompt:'Match each proof habit to its purpose.',interaction:{type:'match',pairs:[['auxiliary line','manufacture known objects'],['what’s special','exploit radii or parallelism'],['work backwards','identify a finishing bridge'],['case audit','cover every configuration'],['dependency order','avoid circular reasoning']]},note:'These five techniques are the reusable payload of the chapter.',coach:['Match each habit to the failure it prevents.']},
 {section:'boss',prompt:'Solo proof: two chords AC and BD cross at B inside a circle. Prove the angle at B is half the sum of its intercepted arcs. Choose the correct skeleton.',interaction:{type:'order',items:['Draw chord DC.','Use the inscribed-angle theorem on the two angles at C and D.','Recognize ∠ABC as an exterior angle of triangle BCD.','Add the remote interior angles to get half the sum of the two arcs.']},hint:'Manufacture a triangle containing the target as an exterior angle.',explain:'Chord DC creates triangle BCD and two inscribed angles. The target is its exterior angle, so it equals their sum—half one arc plus half the other.',walkthrough:['Draw DC.','Translate each new inscribed angle into half its arc.','Use the Exterior Angle Theorem.','Combine the halves.'],coach:['Which chord creates a triangle at B?','Look for an exterior angle, not a triangle sum grind.']}
]};
