/* Chapter 10.6 — The Burden of Proof. Theorems are familiar; proof technique is the payload. */

const PROOF_CIRCLE={view:{x:-7,y:-7,w:14,h:14},alt:'Circle with center O and inscribed angle ACB',points:[{id:'O',x:0,y:0,label:'O'},{id:'A',x:-5,y:-3.32,label:'A'},{id:'B',x:5,y:-3.32,label:'B'},{id:'C',x:0,y:6,label:'C',draggable:true}],circles:[{id:'c',center:'O',r:6}],segments:[{id:'OA',from:'O',to:'A'},{id:'OB',from:'O',to:'B'},{id:'CA',from:'C',to:'A'},{id:'CB',from:'C',to:'B'}]};

export default {id:'lesson-10-4',title:'The Burden of Proof',kicker:'Angles',topicIndex:9,lessonIndex:3,next:'study-path.html',beats:[
  {prompt:'Borrow one triangle fact for this proof studio.',interaction:{type:'reveal',face:'Two sides of a triangle are equal. What must happen to the opposite angles?',cta:'Reveal the loan',hidden:'The opposite angles are equal. Every pair of radii from one circle creates an isosceles triangle.'},note:'This accepted fact is a loan from Chapter 11. Today it turns radii into equal-angle marks.',coach:['Equal sides face equal angles.']},
  {prompt:'Technique 1: exploit what is special. What is special about OA and OB?',interaction:{type:'mcq',options:['They are radii of the same circle, so OA=OB.','They look equal in the drawing.','They are perpendicular.','They are chords.'],correct:0},hint:'Use the definition of a circle.',explain:'Radii of one circle are equal. That turns triangle AOB into an isosceles triangle and unlocks equal base angles.',note:'Technique card: <b>exploit what is special</b>—radii, parallel lines, tangency, and midpoints are structural information.',coach:['Ask why those segments exist.']},
  {prompt:'Technique 2: add an auxiliary line. Connect A to B.',body:'Turn on Auxiliary line and tap A, then B. The new chord creates a triangle whose sides and angles our theorems can grip.',interaction:{type:'geometry',mode:'drag',mustExplore:1,tools:['auxiliary','mark'],instruction:'Draw chord AB.',figure:PROOF_CIRCLE},success:'The construction manufactured an isosceles triangle.',note:'A good auxiliary line creates a familiar object. Its purpose should be nameable before it is drawn.',coach:['Connect the arc endpoints.']},
  {prompt:'Working backwards: the goal is \(\phi=2\theta\). Which question is useful?',interaction:{type:'mcq',options:['What intermediate equality would make \(\phi=2\theta\) immediate?','Which angle looks twice as large?','May I assume the goal?','Can I measure the drawing?'],correct:0},hint:'A goal suggests the bridge you need, not a fact you may use.',explain:'Working backwards identifies a missing claim—such as a sum of labelled angles—that would connect known equations to the target.',note:'Technique card: <b>work backwards from the goal</b>. Ask “what would finish this?” before doing algebra.',coach:['Treat the goal as a destination, never a premise.']},
  {prompt:'Order the main inscribed-angle proof.',interaction:{type:'order',items:['Add radii and the auxiliary chord to create isosceles triangles.','Mark equal base angles forced by equal radii.','Use an exterior-angle or straight-line equation to express the central angle.','Collect the equal pieces to obtain central angle = 2 × inscribed angle.']},hint:'Construction creates equalities; an angle equation assembles them.',explain:'The proof is not a picture trick. Equal radii create isosceles equalities, and an exterior/straight-angle equation combines them into the factor of 2.',note:'The inscribed-angle theorem is powered by <b>radii → isosceles triangles → angle assembly</b>.',coach:['Name the job of each construction.']},
  {prompt:'The proof placed O outside the inscribed angle. Is the theorem finished?',interaction:{type:'mcq',options:['No—center inside and center on a side must also be audited.','Yes—one accurate drawing proves every case.','Yes, because circles are symmetric.','No theorem may have cases.'],correct:0},hint:'Did the construction cover every allowed position of O?',explain:'A proof owns all configurations permitted by its hypotheses. The other cases use nearly the same ingredients, but they must be stated and checked.',note:'Technique card: <b>audit your cases</b>. A convincing special picture is not a universal proof.',coach:['Move the center mentally: inside, outside, on a side.']},
  {prompt:'Two secants proof: which auxiliary segment should you draw?',interaction:{type:'mcq',options:['Join the two far intersection points to create a triangle with inscribed angles.','Draw an unrelated radius.','Draw a diameter through the center regardless of the target.','No construction is allowed.'],correct:0},hint:'Choose the line that manufactures angles with the arcs in the desired formula.',explain:'The far-end chord creates a triangle and two inscribed angles. Supplementary and triangle-sum equations then produce half the far-minus-near arc difference.',note:'Good constructions manufacture objects your existing theorems can grip.',coach:['Work backward from “half two arcs.”']},
  {prompt:'Put the two-secant proof in dependency order.',interaction:{type:'order',items:['Draw the chord between the far intersection points.','Translate the two new inscribed angles into half-arcs.','Use the supplementary angle at the near intersection.','Apply triangle sum and isolate the exterior angle.']},hint:'Do not invoke arc relations before creating their inscribed angles.',explain:'Each step has a job: construct, translate, assemble, isolate.',coach:['Track where every angle comes from.']},
  {prompt:'A tempting tangent–chord proof uses “tangent ⟂ radius.” Why reject it here?',interaction:{type:'mcq',options:['That perpendicular fact was derived from tangent–chord, so using it would be circular.','Perpendicular lines never occur in circles.','Radii are not equal.','The statement is false.'],correct:0},hint:'Trace the dependency arrow backward.',explain:'A theorem cannot be supported by one of its own consequences. True statements can still form an invalid argument when their dependency order loops.',note:'Technique card: <b>dependency order</b>. Never let a theorem stand on its own child.',coach:['Ask how the proposed fact was proved.']},
  {prompt:'Choose the legal tangent–chord route.',interaction:{type:'order',items:['Connect the relevant points to create triangle CAB.','Translate its inscribed angles into half-arcs.','Use the Exterior Angle Theorem at the tangent–chord angle.','Simplify the arc pieces to half the intercepted arc.']},hint:'Chapter 10.3’s exterior-angle theorem is load-bearing.',explain:'The route avoids tangent-radius perpendicularity entirely; it uses only previously established inscribed angles and exterior-angle leverage.',note:'Technique card: <b>exterior-angle leverage</b> often turns two remote half-arcs into the desired whole relation.',coach:['Create a triangle containing the target as an exterior angle.']},
  {prompt:'Proof design: which auxiliary line is strongest for two chords intersecting inside?',interaction:{type:'mcq',options:['Join two endpoints so the target becomes an exterior angle of a triangle.','Draw a random tangent.','Measure both diagonals.','Add a parallel through the center.'],correct:0},hint:'The desired formula is half a sum.',explain:'The chord creates two inscribed angles; the target is their exterior-angle sum, producing half one arc plus half the other.',coach:['Manufacture the two half-arcs you need.']},
  {section:'checkpoint',prompt:'Center O lies on one side of an inscribed angle. Which short proof ingredients suffice?',interaction:{type:'mcq',options:['One isosceles triangle and the Exterior Angle Theorem','Sector area and arc length','Two-secant difference','Coordinate slopes'],correct:0},hint:'The central angle becomes an exterior angle.',explain:'Equal radii create one isosceles triangle; the central angle is its exterior angle, equal to twice a base angle.',coach:['Recognize the easiest deferred case.']},
  {section:'checkpoint',prompt:'Spot the circular argument.',interaction:{type:'mcq',options:['Prove A using B after B was proved using A.','Use a definition in a proof.','Split a proof into cases.','Use vertical angles after proving them.'],correct:0},hint:'Look for a dependency loop.',explain:'If B depends on A, B cannot independently support A. The argument returns to its own starting claim.',coach:['Draw arrows between theorem dependencies.']},
  {section:'checkpoint',prompt:'What is the best reason to draw an auxiliary line?',interaction:{type:'mcq',options:['It creates a known object needed by the goal.','Longer proofs are more rigorous.','Every diagram requires one.','It makes the picture symmetric.'],correct:0},hint:'A construction must have a job.',explain:'Useful lines create isosceles triangles, inscribed angles, parallels, right triangles, or another theorem-ready object.',coach:['Name the object before drawing the line.']},
  {section:'checkpoint',prompt:'A proof handles acute configurations only, but the theorem also allows obtuse ones. What failed?',interaction:{type:'mcq',options:['Case audit','Algebraic simplification','Angle naming','Unit conversion'],correct:0},hint:'The proof did not cover its full hypothesis space.',explain:'A valid derivation for one case may need a sign, order, or extension change in another. Those cases must be addressed.',coach:['List allowed configurations before declaring victory.']},
  {section:'boss',prompt:'Solo proof: two chords AC and BD cross at B inside a circle. Prove \(m\angle ABC\) is half the sum of its intercepted arcs.',interaction:{type:'order',items:['Draw chord DC.','Translate the angles at C and D using the inscribed-angle theorem.','Recognize \(\angle ABC\) as an exterior angle of triangle BCD.','Add the two remote interior half-arcs to obtain half the arc sum.']},hint:'Create a triangle whose exterior angle is the target.',explain:'Chord DC manufactures triangle BCD. Its remote interior angles are half the two relevant arcs; the Exterior Angle Theorem says the target is their sum.',walkthrough:['Choose DC because it creates two useful inscribed angles.','Write each inscribed angle as half an arc.','Apply the exterior-angle theorem.','Factor out one half.'],note:'Technique suit complete: auxiliary lines / what’s special / working backwards / exterior leverage / case audit / dependency order.',coach:['Construction first, translation second, assembly third.']},
]};
