const mcq=(prompt,options,correct,explain,section='learn')=>({section,prompt,interaction:{type:'mcq',options,correct},hint:'Classify the vertex: center, on, inside, or outside the circle.',explain,note:explain,coach:['Locate the vertex first.','Then choose half arc, half sum, or half difference.']});
const fill=(prompt,fields,explain,section='checkpoint')=>({section,prompt,interaction:{type:'fillin',fields},hint:'Choose the relation from the vertex location before substituting.',explain,coach:['Name the configuration.','Substitute the arcs carefully.']});
export default {id:'lesson-10-3',title:'Arcs, Sectors, and Circle Angles',kicker:'Angles',topicIndex:9,lessonIndex:2,next:'interactive-lesson.html?chapter=10&lesson=4',beats:[
 {prompt:'Change the radius. Which arc measurement changes?',interaction:{type:'slider',min:1,max:9,value:3,step:1,label:'radius r',mustExplore:5,render(r){return{main:`For \\(\\theta=\\pi/3\\): arc degrees \\(=60^\\circ\\), arc length \\(=r\\theta=${r}\\pi/3\\)`,sub:'The degree/radian measure belongs to the turn. Length also depends on radius.'};}},note:'Arc measure and arc length are different quantities. A central angle equals its arc’s degree measure.',coach:['Hold θ fixed and watch r.']},
 fill('For r=6 and θ=π/3, find arc length and sector area.',[{label:'arc length',answer:'2pi',accept:['2π']},{label:'sector area',answer:'6pi',accept:['6π']}],'s=rθ=6·π/3=2π. A=θr²/2=(π/3)36/2=6π.','learn'),
 {prompt:'Drag the inscribed vertex P around the circle.',interaction:{type:'geometry',mode:'drag',mustExplore:10,tools:['protractor','mark'],figure:{view:{x:-7,y:-7,w:14,h:14},alt:'Circle with fixed arc AB and draggable inscribed point P',points:[{id:'O',x:0,y:0,label:'O'},{id:'A',x:-4.24,y:-4.24,label:'A'},{id:'B',x:4.24,y:-4.24,label:'B'},{id:'P',x:0,y:6,label:'P',draggable:true,constrain(x,y){const d=Math.hypot(x,y)||1;return [6*x/d,6*y/d];}}],circles:[{id:'c',center:'O',r:6}],segments:[{id:'PA',from:'P',to:'A'},{id:'PB',from:'P',to:'B'},{id:'OA',from:'O',to:'A'},{id:'OB',from:'O',to:'B'}]},measure:s=>{const p=s.points.P,a=s.points.A,b=s.points.B;const u=[a.x-p.x,a.y-p.y],v=[b.x-p.x,b.y-p.y];const d=(u[0]*v[0]+u[1]*v[1])/(Math.hypot(...u)*Math.hypot(...v));return `\\(\\angle APB=${(Math.acos(Math.max(-1,Math.min(1,d)))*180/Math.PI).toFixed(1)}^\\circ\\)`;}},note:'An inscribed angle is half its intercepted arc. Every inscribed angle subtending the same arc is equal.',coach:['Keep A and B fixed; only P moves.']},
 {prompt:'Match vertex location to the relation.',interaction:{type:'match',pairs:[['center','equals its arc'],['on the circle','half the intercepted arc'],['inside the circle','half the sum of arcs'],['outside the circle','half the difference of arcs']]},note:'The location trichotomy is the memory system: ON → half arc; INSIDE → half sum; OUTSIDE → half difference.',coach:['Outside separates arcs, so subtract.']},
 mcq('An angle inscribed in a semicircle measures…',['90°','180°','45°','It depends on radius.'],0,'A semicircle is a 180° arc; an inscribed angle is half, so 90°.'),
 mcq('A tangent and chord cut off a 124° arc. Their angle is…',['62°','124°','248°','56°'],0,'The tangent–chord angle is half its intercepted arc: 62°.'),
 mcq('Two chords cross inside a circle and intercept arcs 60° and 40°. The angle is…',['50°','10°','100°','20°'],0,'Inside means half the sum: (60+40)/2=50°. The supplement is 130°.'),
 fill('Checkpoint: r=8, θ=π/4. Find arc length.',[{label:'s',answer:'2pi',accept:['2π']}],'s=rθ=8·π/4=2π.'),
 mcq('Rapid recognition: two secants meet outside a circle. Which rule fires?',['Half the difference','Half the sum','Half one arc','Equal to the central angle'],0,'Outside vertex → half the difference.','checkpoint'),
 fill('Chords cross inside; intercepted arcs are 86° and 34°. Find the angle.',[{label:'angle',answer:'60'}],'Inside → half the sum: (86+34)/2=60°.'),
 fill('Two tangents meet at P with ∠P=42°. The minor arc is 138°. Find an inscribed angle cutting off that minor arc.',[{label:'angle',answer:'69'}],'An inscribed angle is half its 138° arc: 69°.'),
 {section:'boss',prompt:'Two circles are tangent at G. Vertical angles ∠AGB and ∠DGC are equal. In the first circle ∠E subtends arc AB; in the second ∠F subtends arc DC. Prove the target by giving the common angle.',interaction:{type:'mcq',options:['∠E = ∠AGB = ∠DGC = ∠F','∠E + ∠F = 180°','∠E = 2∠F','No relation follows'],correct:0},hint:'Use same-arc inscribed angles once in each circle, with vertical angles as the bridge.',explain:'In circle 1, ∠E=∠AGB because both subtend arc AB. At G, ∠AGB=∠DGC vertically. In circle 2, ∠DGC=∠F because both subtend arc DC.',walkthrough:['Mark ∠E and ∠AGB as equal in the first circle.','Mark the vertical pair at G.','Mark ∠DGC and ∠F in the second circle.','Read the equality chain.'],coach:['The tangent point G belongs to both circles.','Bridge the circles with vertical angles.']}
]};
