const mcq=(prompt,options,correct,note,section='learn')=>({section,prompt,interaction:{type:'mcq',options,correct},hint:'Name the definition or invariant before calculating.',explain:note,note,coach:['Translate the picture into a definition.','Eliminate choices that violate it.']});
const fill=(prompt,fields,explain,section='checkpoint')=>({section,prompt,interaction:{type:'fillin',fields},hint:'Write the governing relationship first.',explain,coach:['Set up the relationship.','Then substitute and simplify.']});
const angle=(x,y)=>Math.atan2(y,x)*180/Math.PI;
export default {id:'lesson-10-1',title:'Segments, Rays, and Measuring Angles',kicker:'Angles',topicIndex:9,lessonIndex:0,next:'interactive-lesson.html?chapter=10&lesson=2',beats:[
 mcq('Which statement is correct?',['Ray CD and ray DC have different origins.','Ray CD and ray DC are always the same.','A segment has one endpoint.','A line has two endpoints.'],0,'A ray is named origin first. A segment has two endpoints; a line extends both ways.'),
 {prompt:'Drag X along segment AB. Watch the total stay fixed.',interaction:{type:'geometry',mode:'drag',mustExplore:8,figure:{view:{x:-1,y:-3,w:12,h:6},alt:'A segment AB with draggable point X',points:[{id:'A',x:0,y:0,label:'A'},{id:'B',x:10,y:0,label:'B'},{id:'X',x:3,y:0,label:'X',draggable:true,constrain(x){return [Math.max(0,Math.min(10,x)),0];}}],segments:[{id:'AB',from:'A',to:'B'}]},measure:s=>`\\(AX=${s.dist('A','X').toFixed(1)},\ XB=${s.dist('X','B').toFixed(1)},\ AX+XB=10\\)`},note:'If X lies between A and B, then AX + XB = AB.',coach:['Move X; the two pieces trade length.']},
 {prompt:'Build and measure ∠AOB.',body:'Drag A. Turn on the protractor when you want the readout.',interaction:{type:'geometry',mode:'drag',mustExplore:8,tools:['protractor','mark'],figure:{view:{x:-7,y:-7,w:14,h:14},alt:'Two rays OA and OB',points:[{id:'O',x:0,y:0,label:'O'},{id:'B',x:5,y:0,label:'B'},{id:'A',x:2,y:5,label:'A',draggable:true}],segments:[{id:'OA',from:'O',to:'A'},{id:'OB',from:'O',to:'B'}]},measure:s=>{let a=angle(s.points.A.x,s.points.A.y);if(a<0)a+=360;return `\\(\\angle AOB=${a.toFixed(1)}^\\circ\\)`;}},note:'An angle is two rays with a shared origin. In ∠AOB, the vertex O is always in the middle.',coach:['The middle letter names the vertex.']},
 mcq('Why is 360 a useful full-turn unit?',['It has many divisors, so common fractions of a turn are whole numbers.','A circle has 360 sides.','It is prime.','It makes one third equal 33 degrees.'],0,'360 = 2³·3²·5 has 24 divisors. A third is a clean 120°.'),
 {prompt:'Convert 20 5/9° to degrees–minutes–seconds.',interaction:{type:'order',items:['Keep 20 whole degrees.','Multiply 5/9 by 60 to get 33 1/3 minutes.','Keep 33 whole minutes.','Multiply 1/3 by 60 to get 20 seconds.']},hint:'Fractions spill into the next base-60 unit.',explain:'20 5/9° = 20°33′20″.',note:'60 minutes = 1 degree and 60 seconds = 1 minute.',coach:['Multiply the fractional degree by 60.','Repeat with the fractional minute.']},
 mcq('Convert π/3 radians to degrees.',['60°','30°','90°','180°'],0,'Multiply by 180°/π. The π cancels, leaving 60°.'),
 {prompt:'Sort the angle vocabulary.',interaction:{type:'match',pairs:[['less than 90°','acute'],['exactly 90°','right'],['between 90° and 180°','obtuse'],['between 180° and 360°','reflex'],['sum is 90°','complementary']]},note:'Supplementary angles sum to 180°; perpendicular lines meet at 90°.',coach:['Use 90°, 180°, and 360° as the boundaries.']},
 mcq('Checkpoint: two lines cross. Why are vertical angles equal?',['Each is supplementary to the same adjacent angle.','They merely look equal.','They are complementary.','All four angles are equal.'],0,'If α+β=180 and θ+β=180, subtract β: α=θ. Mark equal pairs as soon as you see them.','checkpoint'),
 fill('Checkpoint: convert 7π/6 radians to degrees.',[{label:'degrees',answer:'210',accept:['210°']}],'(7π/6)(180°/π)=210°.'),
 fill('Checkpoint: write 15.4° in DMS.',[{label:'degrees',answer:'15'},{label:'minutes',answer:'24'},{label:'seconds',answer:'0'}],'0.4×60=24, so 15.4°=15°24′00″.'),
 fill('Checkpoint: AX=3 and AB=10. Find XB.',[{label:'XB',answer:'7'}],'AX+XB=AB, so 3+XB=10 and XB=7.'),
 {section:'boss',prompt:'At exactly 4:20, find the smaller angle between the clock hands.',interaction:{type:'fillin',fields:[{label:'angle',answer:'10',accept:['10°']}]},hint:'The minute hand is at 120°. The hour hand has moved one third of the 30° gap from 4 to 5.',explain:'Hour hand: 4×30°+(20/60)×30°=130°. Minute hand: 20×6°=120°. Difference: 10°.',walkthrough:['Place the minute hand: 20 minutes means 120°.','Place the hour hand: it has advanced 10° beyond 4.','Subtract 130°−120°=10°.'],coach:['Track both hands; the hour hand does not freeze at 4.','Each hour gap is 30°.']}
]};
