/* Chapter 12.5 — Rectangles and Squares: dual inheritance. */
export default {id:'lesson-12-3',title:'Rectangles and Squares',kicker:'Quadrilaterals',topicIndex:11,lessonIndex:2,next:'interactive-lesson.html?chapter=12&lesson=4',beats:[
 {prompt:'Why is every rectangle a parallelogram?',interaction:{type:'order',items:['Four equal angles sum to 360°, so each is 90°.','Consecutive angles are supplementary.','Converse same-side-interior tests make opposite sides parallel.','Both opposite pairs parallel: parallelogram.']},hint:'Right angles certify parallel lines.',explain:'The angle constraint forces the parent classification.',note:'Parallelogram + four right angles → rectangle.',coach:['Prove into the hierarchy before inheriting.']},
 {prompt:'Which diagonal properties does a rectangle have?',interaction:{type:'match',pairs:[['bisect each other','inherited from parallelogram'],['equal lengths','new for rectangle'],['perpendicular','not generally true']]},note:'Rectangle vs rhombus: equal diagonals versus perpendicular diagonals.',coach:['Keep the sibling branches separate.']},
 {prompt:'Why are rectangle diagonals equal?',interaction:{type:'mcq',options:['Each is the hypotenuse of a right triangle with legs l and w.','All parallelogram diagonals are equal.','They are perpendicular.','The area formula says so.'],correct:0},hint:'Apply Pythagoras twice.',explain:'Both have length \(\sqrt{l^2+w^2}\).',coach:['Same two legs, same hypotenuse.']},
 {prompt:'Area 40, diagonal 10. Find perimeter.',interaction:{type:'order',items:['Write \(l^2+w^2=100\) and \(lw=40\).','Use \((l+w)^2=l^2+w^2+2lw\).','Obtain \((l+w)^2=180\), so \(l+w=6\sqrt5\).','Double to get perimeter \(12\sqrt5\).']},hint:'The target perimeter wants l+w.',explain:'Chapter 7’s sum/product/power-sum move now solves rectangle geometry.',note:'Translate geometric givens into symmetric algebra before solving l and w separately.',coach:['Target the sum directly.']},
 {prompt:'Center is 5 from one side pair and 3 from the other. Find dimensions and area.',interaction:{type:'fillin',fields:[{label:'length',answer:'10'},{label:'width',answer:'6'},{label:'area',answer:'60'}]},hint:'The center is halfway between each opposite pair.',explain:'Double both distances: 10×6, area 60.',coach:['Center-to-side is half a dimension.']},
 {prompt:'Diagonal 8 makes 30° with a side. Find side lengths.',interaction:{type:'fillin',fields:[{label:'short side',answer:'4'},{label:'long side',answer:'4sqrt(3)',accept:['4√3']}]},hint:'The diagonal creates a 30–60–90 triangle.',explain:'Hypotenuse 8 gives short leg 4 and long leg 4√3.',coach:['Special triangle before formulas.']},
 {prompt:'Square sits at the intersection of which two branches?',interaction:{type:'mcq',options:['Rectangle and rhombus','Trapezoid and kite only','Circle and rectangle','Triangle and rhombus'],correct:0},hint:'It has both all-right-angles and all-equal-sides.',explain:'A square inherits equal diagonals from rectangle and perpendicular diagonals from rhombus; both inherit bisection.',note:'Square is the hierarchy’s conceptual capstone with two parents.',coach:['List inherited properties branch by branch.']},
 {prompt:'Build the square diagonal formulas.',interaction:{type:'fillin',fields:[{label:'side s → diagonal',answer:'ssqrt(2)',accept:['s√2','√2s']},{label:'diagonal d → area',answer:'d^2/2',accept:['d²/2']}]},hint:'Use a 45–45–90 triangle.',explain:'\(d=s\sqrt2\), so \(s^2=d^2/2\).',coach:['Square diagonal is √2, not √3.']},
 {prompt:'Diagonal 8. Find square area.',interaction:{type:'fillin',fields:[{label:'area',answer:'32'}]},hint:'Use d²/2.',explain:'\(64/2=32\).',coach:['No need to solve side first.']},
 {prompt:'What is sufficient to prove a quadrilateral is a square?',interaction:{type:'match',pairs:[['rectangle + adjacent equal sides','square'],['rhombus + one right angle','square'],['equal sides only','rhombus, not enough'],['right angles only','rectangle, not enough']]},note:'To prove square, secure both parent branches.',coach:['One property from each sibling branch.']},
 {prompt:'Prove the side-midpoint figure inside a square is square.',interaction:{type:'order',items:['Join consecutive side midpoints.','Use congruent corner right triangles to prove inner sides equal.','Use 45° corner angles to prove inner angles 90°.','Conclude both rhombus and rectangle conditions.']},hint:'Equal sides alone is not enough.',explain:'Congruence supplies the rhombus branch; angle addition supplies the rectangle branch.',coach:['Prove both parents.']},
 {section:'checkpoint',prompt:'Rectangle diagonal 8 at 30°. Find perimeter.',interaction:{type:'fillin',fields:[{label:'perimeter',answer:'8+8sqrt(3)',accept:['8+8√3']}]},hint:'Double 4+4√3.',explain:'Perimeter \(=2(4+4\sqrt3)\).',coach:['Solve the diagonal triangle.']},
 {section:'checkpoint',prompt:'Width w, length 3w−1, diagonal 37. Find w.',interaction:{type:'fillin',fields:[{label:'w',answer:'12'}]},hint:'Recognize 12–35–37.',explain:'w=12 gives length 35 and the correct triple.',coach:['Triple hunt avoids a quadratic grind.']},
 {section:'checkpoint',prompt:'Which is false for a general rectangle?',interaction:{type:'mcq',options:['Diagonals perpendicular','Diagonals equal','Diagonals bisect','Opposite sides equal'],correct:0},hint:'That property belongs to the rhombus sibling.',explain:'Only a square guarantees both equal and perpendicular diagonals.',coach:['Do not cross inheritance branches.']},
 {section:'checkpoint',prompt:'A rhombus has one right angle. Classify it.',interaction:{type:'mcq',options:['Square','Rectangle only, not square','General rhombus','Impossible'],correct:0},hint:'Parallelogram opposite/consecutive angle rules spread the right angle.',explain:'All four angles become right while all sides remain equal.',coach:['One right angle upgrades the whole rhombus.']},
 {section:'boss',prompt:'Square side 10; points E and F are offset 2 from opposite corners on perpendicular sides. Find EF when horizontal and vertical separations are both 8.',interaction:{type:'fillin',fields:[{label:'EF',answer:'8sqrt(2)',accept:['8√2']}]},hint:'Drop perpendiculars to expose the coordinate differences.',explain:'\(EF=\sqrt{8^2+8^2}=8\sqrt2\).',walkthrough:['Use square sides as perpendicular axes.','Find horizontal separation.','Find vertical separation.','Apply Pythagoras.'],note:'Dropping perpendiculars manufactures the right triangles that rectangle/square problems hide.',coach:['Perpendicular habit first.']},
]};
