/* Chapter 12.6 — Converses, classification, and the orthodiagonal problem studio. */
export default {id:'lesson-12-4',title:'Converses, Classification, and Problem Studio',kicker:'Quadrilaterals',topicIndex:11,lessonIndex:3,next:'study-path.html',beats:[
 {prompt:'Rhombus → perpendicular diagonals. Does the converse follow?',interaction:{type:'mcq',options:['No; a kite is an orthodiagonal counterexample.','Yes; every converse is automatic.','Yes; perpendicular implies bisection.','Only for concave figures.'],correct:0},hint:'Can perpendicular diagonals occur without four equal sides?',explain:'A kite can have perpendicular diagonals without being a rhombus.',note:'A converse is a new claim and needs its own proof.',coach:['Search for a counterexample before assuming reversal.']},
 {prompt:'Repair the converse with one missing hypothesis.',interaction:{type:'order',items:['Assume diagonals are perpendicular and bisect each other.','The four half-diagonals form four right triangles.','Use LL congruence around the intersection.','Harvest four equal outer sides: rhombus.']},hint:'Bisection supplies matching legs.',explain:'Perpendicular plus bisecting is sufficient; perpendicular alone is not.',coach:['Identify exactly what the kite lacked.']},
 {prompt:'Build the minimal classification toolkit.',interaction:{type:'match',pairs:[['diagonals bisect','parallelogram'],['parallelogram + equal diagonals','rectangle'],['parallelogram + perpendicular diagonals','rhombus'],['rhombus + right angle','square']]},note:'Classification runs upward into the hierarchy using sufficient conditions.',coach:['Secure the parent first.']},
 {prompt:'Opposite angles equal. Why parallelogram?',interaction:{type:'order',items:['Let opposite pairs be x,x and y,y.','Angle sum gives 2x+2y=360°, so x+y=180°.','Consecutive angles are supplementary.','Converse same-side-interior tests prove both opposite pairs parallel.']},hint:'Turn opposite equality into consecutive supplementation.',explain:'Angle algebra certifies both pairs of parallel lines.',coach:['The 360° parent property is the bridge.']},
 {prompt:'Prove Varignon’s theorem.',interaction:{type:'order',items:['Join the four side midpoints of any quadrilateral.','Use triangle midlines along diagonal AC.','One inner opposite pair is parallel to AC; the other pair is parallel to BD.','Conclude the midpoint quadrilateral is a parallelogram.']},hint:'The original diagonals control the new sides.',explain:'Each inner side is parallel to—and half of—an original diagonal.',note:'The midpoint quadrilateral exists as a parallelogram for every starting quadrilateral.',coach:['Use Chapter 11 midlines four times.']},
 {prompt:'How do original diagonals upgrade the midpoint quadrilateral?',interaction:{type:'match',pairs:[['perpendicular diagonals','rectangle'],['equal diagonals','rhombus'],['equal + perpendicular diagonals','square']]},note:'One upstream constraint changes the downstream classification.',coach:['Midpoint sides inherit directions and half-lengths.']},
 {prompt:'Derive the orthodiagonal area law.',interaction:{type:'order',items:['Let perpendicular diagonals meet at E.','Split the quadrilateral into four right triangles.','Group their base pieces along each diagonal.','Sum to obtain \(K=d_1d_2/2\).']},hint:'Every small area is half one half-diagonal product.',explain:'The rhombus area formula actually holds for every orthodiagonal quadrilateral.',coach:['Chop and collect.']},
 {prompt:'Orthodiagonal diagonals 12 and 15. Find area.',interaction:{type:'fillin',fields:[{label:'area',answer:'90'}]},hint:'Half the product.',explain:'\(12\cdot15/2=90\).',coach:['No equal-side assumption needed.']},
 {prompt:'Prove the orthodiagonal square identity.',interaction:{type:'order',items:['Write Pythagorean expressions for all four sides using half-diagonal pieces.','Add \(AB^2+CD^2\).','Add \(BC^2+DA^2\).','Each sum contains every half-diagonal square once, so they are equal.']},hint:'Cancellation is the entire mechanism.',explain:'\(AB^2+CD^2=BC^2+DA^2\).',note:'Orthodiagonal vocabulary planted in Build 1 now pays off across area and length identities.',coach:['Label four half-diagonal lengths.']},
 {prompt:'Isosceles orthodiagonal trapezoid bases 10 and 18. Find altitude.',interaction:{type:'fillin',fields:[{label:'height',answer:'14'}]},hint:'This special altitude equals the trapezoid median.',explain:'\(h=(10+18)/2=14\).',coach:['Recognize the orthodiagonal collapse.']},
 {prompt:'Externally tangent circles radii 8 and 11. Find common external tangent segment.',interaction:{type:'fillin',fields:[{label:'length',answer:'4sqrt(22)',accept:['4√22']}]},hint:'Centers are 19 apart; perpendicular offset is 3.',explain:'\(\sqrt{19^2-3^2}=\sqrt{352}=4\sqrt{22}\). The auxiliary radii form a right trapezoid/triangle.',coach:['Subtract radii for the offset.']},
 {section:'checkpoint',prompt:'Parallelogram + equal diagonals ⇒ ?',interaction:{type:'mcq',options:['Rectangle','Rhombus','Kite','Trapezoid only'],correct:0},hint:'Use the classification toolkit.',explain:'Equal diagonals upgrade a parallelogram to rectangle.',coach:['Parent plus new constraint.']},
 {section:'checkpoint',prompt:'Parallelogram + perpendicular diagonals ⇒ ?',interaction:{type:'mcq',options:['Rhombus','Rectangle','General trapezoid','No conclusion'],correct:0},hint:'Sibling branch.',explain:'Perpendicular diagonals upgrade it to a rhombus.',coach:['Do not swap equal and perpendicular.']},
 {section:'checkpoint',prompt:'Original diagonals equal and perpendicular. Midpoint quadrilateral?',interaction:{type:'mcq',options:['Square','Rectangle only','Rhombus only','Kite'],correct:0},hint:'It receives both upgrades.',explain:'Perpendicular gives right angles; equal gives equal sides.',coach:['Two parents meet.']},
 {section:'checkpoint',prompt:'Orthodiagonal sides AB=5, BC=6, CD=7. Find DA.',interaction:{type:'fillin',fields:[{label:'DA',answer:'sqrt(38)',accept:['√38']}]},hint:'Use \(AB^2+CD^2=BC^2+DA^2\).',explain:'\(25+49=36+DA^2\), so \(DA^2=38\).',coach:['Balance opposite square sums.']},
 {section:'boss',prompt:'Prove: midpoint quadrilateral of an equal-diagonal, perpendicular-diagonal quadrilateral is a square.',interaction:{type:'order',items:['Use Varignon to get a parallelogram.','Midpoint sides parallel to perpendicular diagonals give right angles.','Midpoint sides are half equal diagonals, giving equal sides.','Rectangle and rhombus conditions together give square.']},hint:'Transport one original property into each square-parent branch.',explain:'Orthodiagonal supplies rectangle; equidiagonal supplies rhombus; their intersection is square.',walkthrough:['Invoke midlines.','Transport directions.','Transport half-lengths.','Classify through both parents.'],note:'Completed hierarchy: every property was inherited or forced by exactly one added constraint.',coach:['Prove both parent branches.']},
]};
