/* Chapter 12.1–12.2 — Fundamentals and Trapezoids. */
const QUAD={view:{x:-7,y:-5,w:14,h:11},alt:'Draggable quadrilateral ABCD with diagonals',points:[{id:'A',x:-5,y:-3,label:'A',draggable:true},{id:'B',x:5,y:-3,label:'B',draggable:true},{id:'C',x:4,y:4,label:'C',draggable:true},{id:'D',x:-3,y:4,label:'D',draggable:true}],segments:[{id:'AB',from:'A',to:'B'},{id:'BC',from:'B',to:'C'},{id:'CD',from:'C',to:'D'},{id:'DA',from:'D',to:'A'},{id:'AC',from:'A',to:'C',dashed:true},{id:'BD',from:'B',to:'D',dashed:true}]};
export default {id:'lesson-12-1',title:'Fundamentals and Trapezoids',kicker:'Quadrilaterals',topicIndex:11,lessonIndex:0,next:'interactive-lesson.html?chapter=12&lesson=2',beats:[
 {prompt:'Start the hierarchy: what does every child inherit?',interaction:{type:'reveal',face:'Quadrilateral',cta:'Open the hierarchy spine',hidden:'Quadrilateral → trapezoid → parallelogram → rhombus / rectangle → square. Each downward step adds one constraint and keeps every parent property.'},note:'This chapter is a hierarchy, not six unrelated vocabulary lists.',coach:['Read each child as “parent plus one condition.”']},
 {prompt:'Drag one vertex inward until the quadrilateral caves.',interaction:{type:'geometry',mode:'drag',mustExplore:12,tools:['protractor','mark'],instruction:'Explore convex and concave shapes.',figure:QUAD,measure:s=>`\(AC=${s.dist('A','C').toFixed(2)},\ BD=${s.dist('B','D').toFixed(2)}\)`},note:'A concave quadrilateral has one reflex interior angle. Every quadrilateral still has two diagonals, though one may leave the interior.',coach:['Push C across diagonal BD.']},
 {prompt:'Which vertex name is legal?',interaction:{type:'mcq',options:['ABCD, walking around the boundary','ACBD, jumping across a diagonal','ABDC, reversing halfway','Every order is identical'],correct:0},hint:'Consecutive letters must be adjacent vertices.',explain:'Quadrilateral names trace the boundary in one direction. A diagonal jump corrupts side and angle references.',coach:['Walk the perimeter.']},
 {prompt:'Prove the 360° angle sum.',interaction:{type:'order',items:['Draw diagonal AC.','Recognize triangles ABC and ACD.','Add their angle sums: 180°+180°.','Conclude the quadrilateral interior sum is 360°.']},hint:'One diagonal splits the shape without overlap.',explain:'Quadrilateral geometry immediately cashes in Chapter 11’s triangle sum.',note:'Orthodiagonal means the two diagonals are perpendicular—a sleeper word with a major Build 4 payoff.',coach:['Turn a four-sided problem into two triangles.']},
 {prompt:'A trapezoid adds what constraint?',interaction:{type:'mcq',options:['At least one pair of opposite sides parallel','Both pairs parallel','All sides equal','All angles right'],correct:0},hint:'The parallel sides receive a special name.',explain:'The parallel pair are bases; the other sides are legs.',note:'Hierarchy edge: quadrilateral + one parallel pair → trapezoid.',coach:['Do not assume the legs are equal.']},
 {prompt:'Angles along one trapezoid leg are 68° and x. Find x.',interaction:{type:'fillin',fields:[{label:'x',answer:'112'}]},hint:'They are same-side interior angles between parallel bases.',explain:'They are supplementary, so \(x=180-68=112^\circ\).',coach:['Parallel bases create a transversal leg.']},
 {prompt:'Derive the trapezoid median formula.',interaction:{type:'order',items:['Join the midpoints X and Y of the legs.','Use triangle midlines/similarity after drawing a diagonal.','Express the two pieces of XY as half-base contributions.','Add them to obtain \(XY=(b_1+b_2)/2\).']},hint:'A diagonal turns one trapezoid fact into two triangle midline facts.',explain:'The median is the average—not the sum—of the bases.',note:'Trapezoid median joins leg midpoints and is parallel to both bases.',coach:['Diagonal first; triangle tools second.']},
 {prompt:'Bases 8 and 14. Find the median and area when height is 6.',interaction:{type:'fillin',fields:[{label:'median',answer:'11'},{label:'area',answer:'66'}]},hint:'Average the bases, then multiply by height.',explain:'Median \(=(8+14)/2=11\); area \(=11\cdot6=66\).',note:'\(K=(b_1+b_2)h/2=(\text{median})h\). Median is not altitude.',coach:['Average, then height.']},
 {prompt:'Separate three commonly confused trapezoid facts.',interaction:{type:'match',pairs:[['leg-midpoint connector','half the base sum'],['diagonal-midpoint connector','half the base difference'],['isosceles trapezoid legs','equal to each other']]},note:'The midpoint segments live in different places and use sum vs difference; equal legs require the isosceles condition.',coach:['Ask: midpoints of legs or diagonals?']},
 {prompt:'Diagonal-midpoint segment is 3; longer base 97. Find shorter base.',interaction:{type:'fillin',fields:[{label:'shorter base',answer:'91'}]},hint:'\((97-b)/2=3\).',explain:'The difference is 6, so the shorter base is 91.',coach:['This is the difference fact, not the median.']},
 {prompt:'Build the isosceles trapezoid equivalence web.',interaction:{type:'match',pairs:[['equal legs','equal base angles'],['equal base angles','equal diagonals'],['equal diagonals','equal legs']]},note:'Equal legs ⇔ equal base angles ⇔ equal diagonals. Each reverse arrow is a separate converse proof.',coach:['Do not grant these to a general trapezoid.']},
 {section:'checkpoint',prompt:'Median 6, height 3. Find area.',interaction:{type:'fillin',fields:[{label:'area',answer:'18'}]},hint:'Median×height.',explain:'\(6\cdot3=18\).',coach:['No base reconstruction needed.']},
 {section:'checkpoint',prompt:'AB=2·CD, diagonals meet E, AC=11. Find EC.',interaction:{type:'fillin',fields:[{label:'EC',answer:'11/3'}]},hint:'Parallel bases give similar triangles and AE:EC=2:1.',explain:'AC contains three ratio shares, so EC=11/3.',coach:['Use the base ratio on diagonal pieces.']},
 {section:'checkpoint',prompt:'Which property is not automatic for a trapezoid?',interaction:{type:'mcq',options:['Equal legs','Supplementary angles along a leg','A parallel base pair','Angle sum 360°'],correct:0},hint:'Equal legs define a special trapezoid.',explain:'Only an isosceles trapezoid guarantees equal legs.',coach:['Separate parent from special child.']},
 {section:'checkpoint',prompt:'Bases 10 and 18. Find median.',interaction:{type:'fillin',fields:[{label:'median',answer:'14'}]},hint:'Average.',explain:'\((10+18)/2=14\).',coach:['Sum then halve.']},
 {section:'boss',prompt:'Isosceles trapezoid: height 4, legs 8, shorter base 5. Find area.',interaction:{type:'fillin',fields:[{label:'area',answer:'20+16sqrt(3)',accept:['20+16√3']}]},hint:'Drop altitudes from the short base.',explain:'Each overhang is \(\sqrt{8^2-4^2}=4\sqrt3\). Long base \(=5+8\sqrt3\); area \(=20+16\sqrt3\).',walkthrough:['Drop two altitudes.','Solve one right triangle.','Build the long base.','Use average-base times height.'],note:'Dropping altitudes from the short base is the trapezoid workhorse.',coach:['Symmetry gives two equal overhangs.']},
]};
