/* Chapter 12.3–12.4 — Parallelograms and Rhombuses. */
export default {id:'lesson-12-2',title:'Parallelograms and Rhombuses',kicker:'Quadrilaterals',topicIndex:11,lessonIndex:1,next:'interactive-lesson.html?chapter=12&lesson=3',beats:[
 {prompt:'Hierarchy update: what does a parallelogram add?',interaction:{type:'mcq',options:['Both pairs of opposite sides parallel','Equal diagonals','Perpendicular diagonals','Four right angles'],correct:0},hint:'It strengthens the trapezoid parallel condition.',explain:'Both opposite pairs parallel unlock a large inherited property bundle.',note:'Trapezoid + second parallel pair → parallelogram.',coach:['The definition uses parallelism, not equal-looking sides.']},
 {prompt:'One diagonal, four harvested properties.',interaction:{type:'order',items:['Draw diagonal AC.','Mark two alternate-interior angle pairs.','Use shared AC and ASA congruence.','Harvest equal opposite sides and equal opposite angles.']},hint:'Parallelism manufactures the angle pairs.',explain:'One congruence proof yields both opposite-side equalities and both opposite-angle equalities.',coach:['Prove once, harvest repeatedly.']},
 {prompt:'Consecutive angles are supplementary. Why?',interaction:{type:'mcq',options:['They are same-side interior angles between parallel sides.','All parallelogram angles are right.','Opposite angles are supplementary.','Diagonals are perpendicular.'],correct:0},hint:'Use one side as a transversal.',explain:'A+B=180° along each side transversal.',coach:['Parallel lines are the source.']},
 {prompt:'Opposite angles are 3x+20 and 40−x. Solve.',interaction:{type:'fillin',fields:[{label:'x',answer:'5'},{label:'acute angle',answer:'35'},{label:'adjacent angle',answer:'145'}]},hint:'Opposite equal; adjacent supplementary.',explain:'x=5, giving 35° and 145°.',coach:['Use inheritance in two steps.']},
 {prompt:'Prove the diagonals bisect each other.',interaction:{type:'order',items:['Let diagonals meet at E.','Compare triangles ABE and CDE.','Use alternate/vertical angles and an equal opposite-side pair for ASA.','Harvest AE=EC and BE=ED.']},hint:'Choose triangles opposite across E.',explain:'The intersection is the midpoint of both diagonals.',note:'Parallelogram diagonals bisect; they are not generally equal or perpendicular.',coach:['Bisecting means equal halves, not equal wholes.']},
 {prompt:'Match area data to formula.',interaction:{type:'match',pairs:[['base + height','bh'],['adjacent sides + included angle','ab sinB'],['diagonals + included angle','d₁d₂ sinθ/2']]},note:'The sine factor disappears only when the diagonal angle is 90°.',coach:['Inventory the givens.']},
 {prompt:'Sides 3 and 6 include 30°. Find area.',interaction:{type:'fillin',fields:[{label:'area',answer:'9'}]},hint:'\(3\cdot6\sin30^\circ\).',explain:'\(18\cdot1/2=9\).',coach:['Use the included angle.']},
 {prompt:'Area 56 and base 8. Find height and center-to-base distance.',interaction:{type:'fillin',fields:[{label:'height',answer:'7'},{label:'center distance',answer:'3.5',accept:['7/2']}]},hint:'The diagonal intersection is halfway between parallel bases.',explain:'h=7; the center is at half the altitude, 3.5.',coach:['Bisection has a spatial consequence.']},
 {prompt:'A rhombus adds which new constraint?',interaction:{type:'mcq',options:['All four sides equal','All angles right','Diagonals equal','Only one parallel pair'],correct:0},hint:'It remains a parallelogram.',explain:'A rhombus inherits every parallelogram property, then adds equal sides.',note:'Inheritance first; new perpendicular-diagonal property second.',coach:['Do not relearn inherited facts.']},
 {prompt:'Why are rhombus diagonals perpendicular?',interaction:{type:'order',items:['Use inherited diagonal bisection.','Compare adjacent triangles sharing a half-diagonal.','SSS gives equal adjacent angles at the intersection.','Equal linear-pair angles are each 90°.']},hint:'Equal plus supplementary forces right angles.',explain:'The equal-side constraint upgrades bisecting diagonals to perpendicular bisectors.',coach:['Use what the parent already gave.']},
 {prompt:'Rhombus side 13, diagonal 24. Find other diagonal and area.',interaction:{type:'fillin',fields:[{label:'other diagonal',answer:'10'},{label:'area',answer:'120'}]},hint:'Half-diagonals form 5–12–13.',explain:'Other half is 5, so full diagonal 10; area \(24\cdot10/2=120\).',coach:['Halve before Pythagoras.']},
 {section:'checkpoint',prompt:'Which is false for a general parallelogram?',interaction:{type:'mcq',options:['Diagonals are equal','Diagonals bisect','Opposite sides equal','Opposite angles equal'],correct:0},hint:'Equal diagonals belong to rectangles.',explain:'Only bisection is guaranteed.',coach:['Do not borrow from a child shape.']},
 {section:'checkpoint',prompt:'Rhombus diagonals 8 and 10. Find area.',interaction:{type:'fillin',fields:[{label:'area',answer:'40'}]},hint:'Perpendicular diagonals.',explain:'\(8\cdot10/2=40\).',coach:['The sine is 1.']},
 {section:'checkpoint',prompt:'General parallelogram diagonals 8,10 meet at 30°. Find area.',interaction:{type:'fillin',fields:[{label:'area',answer:'20'}]},hint:'Keep sin30°.',explain:'\(8\cdot10\cdot(1/2)/2=20\).',coach:['Do not use the rhombus shortcut.']},
 {section:'checkpoint',prompt:'A cyclic rhombus must be what?',interaction:{type:'mcq',options:['Square','General kite','Non-square rectangle impossible','Trapezoid only'],correct:0},hint:'Opposite angles in a cyclic quad are supplementary and in a rhombus are equal.',explain:'Equal and supplementary forces 90°, so the rhombus is a square.',coach:['Combine properties from two classifications.']},
 {section:'boss',prompt:'Area 40; rhombus diagonals 2x and 3x−2. Find x and side.',interaction:{type:'fillin',fields:[{label:'x',answer:'4'},{label:'side',answer:'sqrt(41)',accept:['√41']}]},hint:'Use area, then half-diagonal right triangle.',explain:'\((2x)(3x-2)/2=40\Rightarrow x=4\). Halves 4 and 5 give side √41.',walkthrough:['Build the area equation.','Reject the negative root.','Halve both diagonals.','Apply Pythagoras.'],note:'Diagonal data turns rhombus problems into right-triangle problems.',coach:['Inheritance supplies bisection and perpendicularity.']},
]};
